--ONET ACCOUNTS TABLE INITAL POUPULATE--

INSERT INTO ACCOUNTS values(1,Morgan Has,MHas366@icloud.com);
INSERT INTO ACCOUNTS values(2,Oscar Loson,OLoson560@yahoo.com);
INSERT INTO ACCOUNTS values(3,Sydney Leasure,SLeasure615@hotmail.com);
INSERT INTO ACCOUNTS values(4,Octavio Talsma,OTalsma32@yahoo.com);
INSERT INTO ACCOUNTS values(5,Vern Bosley,VBosley84@yahoo.com);
INSERT INTO ACCOUNTS values(6,Monte Wendlandt,MWendlandt412@msn.com);
INSERT INTO ACCOUNTS values(7,Bethanie Tankson,BTankson35@icloud.com);
INSERT INTO ACCOUNTS values(8,Chris Hapeman,CHapeman182@yahoo.com);
INSERT INTO ACCOUNTS values(9,Andrew Mesia,AMesia23@hotmail.com);
INSERT INTO ACCOUNTS values(10,Reginald Spiva,RSpiva579@icloud.com);
INSERT INTO ACCOUNTS values(11,Lajuana Battenhouse,LBattenhouse794@icloud.com);
INSERT INTO ACCOUNTS values(12,Lin Isreal,LIsreal918@icloud.com);
INSERT INTO ACCOUNTS values(13,Wilber Gavette,WGavette477@yahoo.com);
INSERT INTO ACCOUNTS values(14,Andreas Wiechert,AWiechert153@icloud.com);
INSERT INTO ACCOUNTS values(15,Michel Seabrook,MSeabrook945@icloud.com;
INSERT INTO ACCOUNTS values(16,Tamisha Melgar,TMelgar570@msn.com);
INSERT INTO ACCOUNTS values(17,Maurice Dalbeck,MDalbeck773@yahoo.com);
INSERT INTO ACCOUNTS values(18,Suanne Phaymany,SPhaymany50@yahoo.com);
INSERT INTO ACCOUNTS values(19,Dean Zimbelman,DZimbelman148@hotmail.com);
INSERT INTO ACCOUNTS values(20,Salome Lawhead,SLawhead118@gmail.com);
INSERT INTO ACCOUNTS values(21,Arvilla Mcclurg,AMcclurg955@hotmail.com);
INSERT INTO ACCOUNTS values(22,Shery Snyder,SSnyder946@yahoo.com);
INSERT INTO ACCOUNTS values(23,Jong Underkofler,JUnderkofler587@hotmail.com);
INSERT INTO ACCOUNTS values(24,Michel Aderhold,MAderhold29@yahoo.com);
