
INSERT INTO AnswerOptions values(1,1,1,'Agriculture');
INSERT INTO AnswerOptions values(1,1,2,'Bioinformatics and/or computational biology');
INSERT INTO AnswerOptions values(1,1,3,'Discipline-based education research (DBER)');
INSERT INTO AnswerOptions values(1,1,4,'Engineering');
INSERT INTO AnswerOptions values(1,1,5,'Computer science and computer engineering');
INSERT INTO AnswerOptions values(1,1,6,'Engineering - Biomedical');
INSERT INTO AnswerOptions values(1,1,7,'Engineering (other)');
INSERT INTO AnswerOptions values(1,1,8,'Environmental science');
INSERT INTO AnswerOptions values(1,1,9,'Kinesiology');
INSERT INTO AnswerOptions values(1,1,10,'anatomy and physiology ');
INSERT INTO AnswerOptions values(1,1,11,'biochemistry');
INSERT INTO AnswerOptions values(1,1,12,'general biology');
INSERT INTO AnswerOptions values(1,1,13,'botany');
INSERT INTO AnswerOptions values(1,1,14,'ecology');
INSERT INTO AnswerOptions values(1,1,15,'evolution');
INSERT INTO AnswerOptions values(1,1,16,'genetics ');
INSERT INTO AnswerOptions values(1,1,17,'zoology');
INSERT INTO AnswerOptions values(1,1,18,'Marine science');
INSERT INTO AnswerOptions values(1,1,19,'Mathematics');
INSERT INTO AnswerOptions values(1,1,20,'Neuroscience');
INSERT INTO AnswerOptions values(1,1,21,'Physical Sciences:');
INSERT INTO AnswerOptions values(1,1,22,'Astronomy');
INSERT INTO AnswerOptions values(1,1,23,'Chemistry ');
INSERT INTO AnswerOptions values(1,1,24,'Physics');
INSERT INTO AnswerOptions values(1,1,25,'Geology');
INSERT INTO AnswerOptions values(1,1,26,'Soil science');
INSERT INTO AnswerOptions values(1,1,27,'Statistics and/or Data Science');
INSERT INTO AnswerOptions values(1,1,28,'Other');
INSERT INTO AnswerOptions values(1,1,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,2,1,'1 student');
INSERT INTO AnswerOptions values(1,2,2,'2-4 students');
INSERT INTO AnswerOptions values(1,2,3,'5-8 students');
INSERT INTO AnswerOptions values(1,2,4,'9-12 students');
INSERT INTO AnswerOptions values(1,2,5,'more than 12 students');
INSERT INTO AnswerOptions values(1,2,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,3,1,'2 ');
INSERT INTO AnswerOptions values(1,3,2,'3-5 ');
INSERT INTO AnswerOptions values(1,3,3,'6-9');
INSERT INTO AnswerOptions values(1,3,4,'10-13');
INSERT INTO AnswerOptions values(1,3,5,'More than 13');
INSERT INTO AnswerOptions values(1,3,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,4,1,'Faculty member');
INSERT INTO AnswerOptions values(1,4,2,'Postdoctoral researcher');
INSERT INTO AnswerOptions values(1,4,3,'"Graduate student');
INSERT INTO AnswerOptions values(1,4,4,'Other');
INSERT INTO AnswerOptions values(1,4,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,5,1,'Laboratory research');
INSERT INTO AnswerOptions values(1,5,2,'Field research');
INSERT INTO AnswerOptions values(1,5,3,'Computer-based research');
INSERT INTO AnswerOptions values(1,5,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,6,1,'0 hours a week');
INSERT INTO AnswerOptions values(1,6,2,'1 - 5 hours a week');
INSERT INTO AnswerOptions values(1,6,3,'6 - 10 hours a week');
INSERT INTO AnswerOptions values(1,6,4,'11 - 15 hours a week');
INSERT INTO AnswerOptions values(1,6,5,'16 - 20 hours a week');
INSERT INTO AnswerOptions values(1,6,6,'21 - 25 hours a week');
INSERT INTO AnswerOptions values(1,6,7,'26 - 30 hours a week');
INSERT INTO AnswerOptions values(1,6,8,'more than 30 hours a week');
INSERT INTO AnswerOptions values(1,6,0,'Prefer not to say');
INSERT INTO AnswerOptions values(1,12,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,12,2,' disagree');
INSERT INTO AnswerOptions values(1,12,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,12,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,12,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,12,6,'agree');
INSERT INTO AnswerOptions values(1,12,7,'strongly agree');
INSERT INTO AnswerOptions values(1,12,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,1,1,'Academic (college or university)');
INSERT INTO AnswerOptions values(2,1,2,'Industry - research and development');
INSERT INTO AnswerOptions values(2,1,3,'Industry - production and quality control');
INSERT INTO AnswerOptions values(2,1,4,'Government ');
INSERT INTO AnswerOptions values(2,1,5,'Self-employed consulting/fee for service');
INSERT INTO AnswerOptions values(2,1,6,'Other');
INSERT INTO AnswerOptions values(2,1,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,2,1,'AA - year');
INSERT INTO AnswerOptions values(2,2,2,'Baccalaureate - year');
INSERT INTO AnswerOptions values(2,2,3,'Masters of Science');
INSERT INTO AnswerOptions values(2,2,4,'Ph. D');
INSERT INTO AnswerOptions values(2,2,5,'JD');
INSERT INTO AnswerOptions values(2,2,6,'MD');
INSERT INTO AnswerOptions values(2,2,7,'MBA');
INSERT INTO AnswerOptions values(2,2,8,'not applicable ');
INSERT INTO AnswerOptions values(2,2,0,'Prefer not to answer');
