---Profile: 1 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',1,5.3);
INSERT INTO RealValues ('Decision Making Autonomy',1,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',1,4.0);
INSERT INTO RealValues ('Task Variety',1,6.5);
INSERT INTO RealValues ('Task Significance',1,6.3);
INSERT INTO RealValues ('Task Identity',1,4.8);
INSERT INTO RealValues ('Feedback from Job',1,4.7);
INSERT INTO RealValues ('Job Complexity',1,6.0);
INSERT INTO RealValues ('Information Processing',1,4.8);
INSERT INTO RealValues ('Problem Solving',1,5.8);
INSERT INTO RealValues ('Skill Variety',1,5.0);
INSERT INTO RealValues ('Specialization',1,4.0);
INSERT INTO RealValues ('Social Support',1,4.0);
INSERT INTO RealValues ('Initiated Interdependence ',1,4.3);
INSERT INTO RealValues ('Received Interdependence',1,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',1,5.8);
INSERT INTO RealValues ('Feedback from Others',1,4.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',1,5.3);
INSERT INTO RealValues ('Peer Feedback',1,3.3);
INSERT INTO RealValues ('Ergonomics',1,3.0);
INSERT INTO RealValues ('Physical Demands',1,5.7);
INSERT INTO RealValues ('Work Conditions',1,5.2);
INSERT INTO RealValues ('Equipment Use',1,4.0
);
---Profile: 2 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',2,3.3);
INSERT INTO RealValues ('Decision Making Autonomy',2,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',2,2.7);
INSERT INTO RealValues ('Task Variety',2,5.8);
INSERT INTO RealValues ('Task Significance',2,5.8);
INSERT INTO RealValues ('Task Identity',2,4.0);
INSERT INTO RealValues ('Feedback from Job',2,4.3);
INSERT INTO RealValues ('Job Complexity',2,4.5);
INSERT INTO RealValues ('Information Processing',2,3.8);
INSERT INTO RealValues ('Problem Solving',2,5.8);
INSERT INTO RealValues ('Skill Variety',2,4.0);
INSERT INTO RealValues ('Specialization',2,4.0);
INSERT INTO RealValues ('Social Support',2,2.0);
INSERT INTO RealValues ('Initiated Interdependence ',2,4.3);
INSERT INTO RealValues ('Received Interdependence',2,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',2,5.0);
INSERT INTO RealValues ('Feedback from Others',2,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',2,2.0);
INSERT INTO RealValues ('Peer Feedback',2,1.3);
INSERT INTO RealValues ('Ergonomics',2,3.0);
INSERT INTO RealValues ('Physical Demands',2,5.7);
INSERT INTO RealValues ('Work Conditions',2,4.8);
INSERT INTO RealValues ('Equipment Use',2,2.7
);
---Profile: 3 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',3,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',3,3.7);
INSERT INTO RealValues ('Work Methods Autonomy',3,4.7);
INSERT INTO RealValues ('Task Variety',3,5.5);
INSERT INTO RealValues ('Task Significance',3,6.5);
INSERT INTO RealValues ('Task Identity',3,5.0);
INSERT INTO RealValues ('Feedback from Job',3,4.7);
INSERT INTO RealValues ('Job Complexity',3,5.0);
INSERT INTO RealValues ('Information Processing',3,4.8);
INSERT INTO RealValues ('Problem Solving',3,5.5);
INSERT INTO RealValues ('Skill Variety',3,4.5);
INSERT INTO RealValues ('Specialization',3,5.3);
INSERT INTO RealValues ('Social Support',3,3.0);
INSERT INTO RealValues ('Initiated Interdependence ',3,4.0);
INSERT INTO RealValues ('Received Interdependence',3,7.0);
INSERT INTO RealValues ('Interaction Outside Research Group',3,5.5);
INSERT INTO RealValues ('Feedback from Others',3,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',3,3.0);
INSERT INTO RealValues ('Peer Feedback',3,2.3);
INSERT INTO RealValues ('Ergonomics',3,3.7);
INSERT INTO RealValues ('Physical Demands',3,5.3);
INSERT INTO RealValues ('Work Conditions',3,5.8);
INSERT INTO RealValues ('Equipment Use',3,4.0
);
---Profile: 4 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',4,4.7);
INSERT INTO RealValues ('Decision Making Autonomy',4,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',4,2.7);
INSERT INTO RealValues ('Task Variety',4,4.0);
INSERT INTO RealValues ('Task Significance',4,3.5);
INSERT INTO RealValues ('Task Identity',4,2.3);
INSERT INTO RealValues ('Feedback from Job',4,2.7);
INSERT INTO RealValues ('Job Complexity',4,3.3);
INSERT INTO RealValues ('Information Processing',4,1.8);
INSERT INTO RealValues ('Problem Solving',4,3.3);
INSERT INTO RealValues ('Skill Variety',4,2.8);
INSERT INTO RealValues ('Specialization',4,2.3);
INSERT INTO RealValues ('Social Support',4,1.7);
INSERT INTO RealValues ('Initiated Interdependence ',4,2.3);
INSERT INTO RealValues ('Received Interdependence',4,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',4,3.0);
INSERT INTO RealValues ('Feedback from Others',4,1.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',4,2.0);
INSERT INTO RealValues ('Peer Feedback',4,1.0);
INSERT INTO RealValues ('Ergonomics',4,2.7);
INSERT INTO RealValues ('Physical Demands',4,3.3);
INSERT INTO RealValues ('Work Conditions',4,2.8);
INSERT INTO RealValues ('Equipment Use',4,2.0
);
---Profile: 5 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',5,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',5,5.7);
INSERT INTO RealValues ('Work Methods Autonomy',5,5.7);
INSERT INTO RealValues ('Task Variety',5,6.5);
INSERT INTO RealValues ('Task Significance',5,5.8);
INSERT INTO RealValues ('Task Identity',5,5.3);
INSERT INTO RealValues ('Feedback from Job',5,3.7);
INSERT INTO RealValues ('Job Complexity',5,5.3);
INSERT INTO RealValues ('Information Processing',5,4.8);
INSERT INTO RealValues ('Problem Solving',5,5.0);
INSERT INTO RealValues ('Skill Variety',5,3.8);
INSERT INTO RealValues ('Specialization',5,4.3);
INSERT INTO RealValues ('Social Support',5,3.0);
INSERT INTO RealValues ('Initiated Interdependence ',5,4.0);
INSERT INTO RealValues ('Received Interdependence',5,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',5,5.0);
INSERT INTO RealValues ('Feedback from Others',5,4.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',5,6.0);
INSERT INTO RealValues ('Peer Feedback',5,2.3);
INSERT INTO RealValues ('Ergonomics',5,4.0);
INSERT INTO RealValues ('Physical Demands',5,5.7);
INSERT INTO RealValues ('Work Conditions',5,4.8);
INSERT INTO RealValues ('Equipment Use',5,3.0
);
---Profile: 6 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',6,3.3);
INSERT INTO RealValues ('Decision Making Autonomy',6,6.3);
INSERT INTO RealValues ('Work Methods Autonomy',6,5.3);
INSERT INTO RealValues ('Task Variety',6,6.3);
INSERT INTO RealValues ('Task Significance',6,4.3);
INSERT INTO RealValues ('Task Identity',6,3.8);
INSERT INTO RealValues ('Feedback from Job',6,4.0);
INSERT INTO RealValues ('Job Complexity',6,4.8);
INSERT INTO RealValues ('Information Processing',6,3.3);
INSERT INTO RealValues ('Problem Solving',6,4.5);
INSERT INTO RealValues ('Skill Variety',6,3.5);
INSERT INTO RealValues ('Specialization',6,4.5);
INSERT INTO RealValues ('Social Support',6,1.7);
INSERT INTO RealValues ('Initiated Interdependence ',6,3.3);
INSERT INTO RealValues ('Received Interdependence',6,5.7);
INSERT INTO RealValues ('Interaction Outside Research Group',6,4.3);
INSERT INTO RealValues ('Feedback from Others',6,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',6,2.0);
INSERT INTO RealValues ('Peer Feedback',6,2.3);
INSERT INTO RealValues ('Ergonomics',6,3.0);
INSERT INTO RealValues ('Physical Demands',6,5.7);
INSERT INTO RealValues ('Work Conditions',6,4.8);
INSERT INTO RealValues ('Equipment Use',6,2.7
);
---Profile: 7 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',7,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',7,4.7);
INSERT INTO RealValues ('Work Methods Autonomy',7,5.7);
INSERT INTO RealValues ('Task Variety',7,7.0);
INSERT INTO RealValues ('Task Significance',7,3.5);
INSERT INTO RealValues ('Task Identity',7,4.8);
INSERT INTO RealValues ('Feedback from Job',7,5.0);
INSERT INTO RealValues ('Job Complexity',7,5.8);
INSERT INTO RealValues ('Information Processing',7,4.0);
INSERT INTO RealValues ('Problem Solving',7,5.0);
INSERT INTO RealValues ('Skill Variety',7,5.3);
INSERT INTO RealValues ('Specialization',7,4.8);
INSERT INTO RealValues ('Social Support',7,2.2);
INSERT INTO RealValues ('Initiated Interdependence ',7,4.3);
INSERT INTO RealValues ('Received Interdependence',7,6.0);
INSERT INTO RealValues ('Interaction Outside Research Group',7,5.0);
INSERT INTO RealValues ('Feedback from Others',7,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',7,3.3);
INSERT INTO RealValues ('Peer Feedback',7,2.7);
INSERT INTO RealValues ('Ergonomics',7,4.0);
INSERT INTO RealValues ('Physical Demands',7,6.3);
INSERT INTO RealValues ('Work Conditions',7,5.0);
INSERT INTO RealValues ('Equipment Use',7,3.7
);
---Profile: 8 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',8,1.0);
INSERT INTO RealValues ('Decision Making Autonomy',8,2.0);
INSERT INTO RealValues ('Work Methods Autonomy',8,5.0);
INSERT INTO RealValues ('Task Variety',8,3.5);
INSERT INTO RealValues ('Task Significance',8,4.0);
INSERT INTO RealValues ('Task Identity',8,2.5);
INSERT INTO RealValues ('Feedback from Job',8,2.0);
INSERT INTO RealValues ('Job Complexity',8,2.8);
INSERT INTO RealValues ('Information Processing',8,1.8);
INSERT INTO RealValues ('Problem Solving',8,3.3);
INSERT INTO RealValues ('Skill Variety',8,2.0);
INSERT INTO RealValues ('Specialization',8,2.5);
INSERT INTO RealValues ('Social Support',8,1.3);
INSERT INTO RealValues ('Initiated Interdependence ',8,2.0);
INSERT INTO RealValues ('Received Interdependence',8,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',8,2.8);
INSERT INTO RealValues ('Feedback from Others',8,1.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',8,1.0);
INSERT INTO RealValues ('Peer Feedback',8,1.0);
INSERT INTO RealValues ('Ergonomics',8,1.7);
INSERT INTO RealValues ('Physical Demands',8,3.3);
INSERT INTO RealValues ('Work Conditions',8,3.0);
INSERT INTO RealValues ('Equipment Use',8,3.0
);
---Profile: 9 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',9,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',9,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',9,4.0);
INSERT INTO RealValues ('Task Variety',9,5.3);
INSERT INTO RealValues ('Task Significance',9,5.0);
INSERT INTO RealValues ('Task Identity',9,4.8);
INSERT INTO RealValues ('Feedback from Job',9,4.7);
INSERT INTO RealValues ('Job Complexity',9,6.0);
INSERT INTO RealValues ('Information Processing',9,4.3);
INSERT INTO RealValues ('Problem Solving',9,5.8);
INSERT INTO RealValues ('Skill Variety',9,5.0);
INSERT INTO RealValues ('Specialization',9,4.8);
INSERT INTO RealValues ('Social Support',9,4.2);
INSERT INTO RealValues ('Initiated Interdependence ',9,4.3);
INSERT INTO RealValues ('Received Interdependence',9,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',9,5.8);
INSERT INTO RealValues ('Feedback from Others',9,4.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',9,5.3);
INSERT INTO RealValues ('Peer Feedback',9,3.3);
INSERT INTO RealValues ('Ergonomics',9,3.0);
INSERT INTO RealValues ('Physical Demands',9,3.7);
INSERT INTO RealValues ('Work Conditions',9,5.2);
INSERT INTO RealValues ('Equipment Use',9,7.0
);
---Profile: 10 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',10,1.3);
INSERT INTO RealValues ('Decision Making Autonomy',10,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',10,4.0);
INSERT INTO RealValues ('Task Variety',10,5.3);
INSERT INTO RealValues ('Task Significance',10,5.0);
INSERT INTO RealValues ('Task Identity',10,4.0);
INSERT INTO RealValues ('Feedback from Job',10,4.3);
INSERT INTO RealValues ('Job Complexity',10,4.5);
INSERT INTO RealValues ('Information Processing',10,3.3);
INSERT INTO RealValues ('Problem Solving',10,5.8);
INSERT INTO RealValues ('Skill Variety',10,4.0);
INSERT INTO RealValues ('Specialization',10,4.3);
INSERT INTO RealValues ('Social Support',10,2.2);
INSERT INTO RealValues ('Initiated Interdependence ',10,4.3);
INSERT INTO RealValues ('Received Interdependence',10,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',10,5.0);
INSERT INTO RealValues ('Feedback from Others',10,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',10,2.0);
INSERT INTO RealValues ('Peer Feedback',10,1.3);
INSERT INTO RealValues ('Ergonomics',10,3.0);
INSERT INTO RealValues ('Physical Demands',10,4.0);
INSERT INTO RealValues ('Work Conditions',10,3.8);
INSERT INTO RealValues ('Equipment Use',10,2.7
);
---Profile: 11 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',11,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',11,3.7);
INSERT INTO RealValues ('Work Methods Autonomy',11,4.7);
INSERT INTO RealValues ('Task Variety',11,6.3);
INSERT INTO RealValues ('Task Significance',11,6.5);
INSERT INTO RealValues ('Task Identity',11,4.0);
INSERT INTO RealValues ('Feedback from Job',11,4.7);
INSERT INTO RealValues ('Job Complexity',11,4.3);
INSERT INTO RealValues ('Information Processing',11,4.8);
INSERT INTO RealValues ('Problem Solving',11,5.5);
INSERT INTO RealValues ('Skill Variety',11,5.0);
INSERT INTO RealValues ('Specialization',11,5.3);
INSERT INTO RealValues ('Social Support',11,3.0);
INSERT INTO RealValues ('Initiated Interdependence ',11,4.0);
INSERT INTO RealValues ('Received Interdependence',11,7.0);
INSERT INTO RealValues ('Interaction Outside Research Group',11,5.5);
INSERT INTO RealValues ('Feedback from Others',11,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',11,3.0);
INSERT INTO RealValues ('Peer Feedback',11,2.3);
INSERT INTO RealValues ('Ergonomics',11,3.7);
INSERT INTO RealValues ('Physical Demands',11,5.3);
INSERT INTO RealValues ('Work Conditions',11,4.0);
INSERT INTO RealValues ('Equipment Use',11,5.0
);
---Profile: 12 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',12,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',12,3.3);
INSERT INTO RealValues ('Work Methods Autonomy',12,2.7);
INSERT INTO RealValues ('Task Variety',12,4.3);
INSERT INTO RealValues ('Task Significance',12,3.5);
INSERT INTO RealValues ('Task Identity',12,2.3);
INSERT INTO RealValues ('Feedback from Job',12,2.7);
INSERT INTO RealValues ('Job Complexity',12,2.3);
INSERT INTO RealValues ('Information Processing',12,1.8);
INSERT INTO RealValues ('Problem Solving',12,3.3);
INSERT INTO RealValues ('Skill Variety',12,2.8);
INSERT INTO RealValues ('Specialization',12,2.3);
INSERT INTO RealValues ('Social Support',12,1.8);
INSERT INTO RealValues ('Initiated Interdependence ',12,2.3);
INSERT INTO RealValues ('Received Interdependence',12,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',12,3.3);
INSERT INTO RealValues ('Feedback from Others',12,1.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',12,2.0);
INSERT INTO RealValues ('Peer Feedback',12,1.0);
INSERT INTO RealValues ('Ergonomics',12,2.7);
INSERT INTO RealValues ('Physical Demands',12,2.3);
INSERT INTO RealValues ('Work Conditions',12,2.4);
INSERT INTO RealValues ('Equipment Use',12,4.0
);
---Profile: 13 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',13,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',13,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',13,3.3);
INSERT INTO RealValues ('Task Variety',13,6.8);
INSERT INTO RealValues ('Task Significance',13,5.8);
INSERT INTO RealValues ('Task Identity',13,4.0);
INSERT INTO RealValues ('Feedback from Job',13,3.7);
INSERT INTO RealValues ('Job Complexity',13,5.0);
INSERT INTO RealValues ('Information Processing',13,4.8);
INSERT INTO RealValues ('Problem Solving',13,6.0);
INSERT INTO RealValues ('Skill Variety',13,5.3);
INSERT INTO RealValues ('Specialization',13,5.3);
INSERT INTO RealValues ('Social Support',13,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',13,2.3);
INSERT INTO RealValues ('Received Interdependence',13,4.3);
INSERT INTO RealValues ('Interaction Outside Research Group',13,5.0);
INSERT INTO RealValues ('Feedback from Others',13,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',13,6.0);
INSERT INTO RealValues ('Peer Feedback',13,1.7);
INSERT INTO RealValues ('Ergonomics',13,3.0);
INSERT INTO RealValues ('Physical Demands',13,4.7);
INSERT INTO RealValues ('Work Conditions',13,4.8);
INSERT INTO RealValues ('Equipment Use',13,3.0
);
---Profile: 14 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',14,3.3);
INSERT INTO RealValues ('Decision Making Autonomy',14,4.7);
INSERT INTO RealValues ('Work Methods Autonomy',14,4.7);
INSERT INTO RealValues ('Task Variety',14,6.3);
INSERT INTO RealValues ('Task Significance',14,5.3);
INSERT INTO RealValues ('Task Identity',14,4.0);
INSERT INTO RealValues ('Feedback from Job',14,4.0);
INSERT INTO RealValues ('Job Complexity',14,3.8);
INSERT INTO RealValues ('Information Processing',14,3.8);
INSERT INTO RealValues ('Problem Solving',14,4.8);
INSERT INTO RealValues ('Skill Variety',14,4.3);
INSERT INTO RealValues ('Specialization',14,4.8);
INSERT INTO RealValues ('Social Support',14,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',14,3.0);
INSERT INTO RealValues ('Received Interdependence',14,5.7);
INSERT INTO RealValues ('Interaction Outside Research Group',14,3.8);
INSERT INTO RealValues ('Feedback from Others',14,2.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',14,2.0);
INSERT INTO RealValues ('Peer Feedback',14,1.7);
INSERT INTO RealValues ('Ergonomics',14,3.0);
INSERT INTO RealValues ('Physical Demands',14,5.7);
INSERT INTO RealValues ('Work Conditions',14,4.8);
INSERT INTO RealValues ('Equipment Use',14,2.7
);
---Profile: 15 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',15,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',15,4.0);
INSERT INTO RealValues ('Work Methods Autonomy',15,4.7);
INSERT INTO RealValues ('Task Variety',15,7.0);
INSERT INTO RealValues ('Task Significance',15,6.3);
INSERT INTO RealValues ('Task Identity',15,5.3);
INSERT INTO RealValues ('Feedback from Job',15,3.0);
INSERT INTO RealValues ('Job Complexity',15,4.3);
INSERT INTO RealValues ('Information Processing',15,4.0);
INSERT INTO RealValues ('Problem Solving',15,5.5);
INSERT INTO RealValues ('Skill Variety',15,5.3);
INSERT INTO RealValues ('Specialization',15,5.3);
INSERT INTO RealValues ('Social Support',15,2.8);
INSERT INTO RealValues ('Initiated Interdependence ',15,5.0);
INSERT INTO RealValues ('Received Interdependence',15,4.3);
INSERT INTO RealValues ('Interaction Outside Research Group',15,3.5);
INSERT INTO RealValues ('Feedback from Others',15,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',15,2.0);
INSERT INTO RealValues ('Peer Feedback',15,2.0);
INSERT INTO RealValues ('Ergonomics',15,4.0);
INSERT INTO RealValues ('Physical Demands',15,6.3);
INSERT INTO RealValues ('Work Conditions',15,5.0);
INSERT INTO RealValues ('Equipment Use',15,3.7
);
---Profile: 16 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',16,1.0);
INSERT INTO RealValues ('Decision Making Autonomy',16,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',16,4.0);
INSERT INTO RealValues ('Task Variety',16,4.0);
INSERT INTO RealValues ('Task Significance',16,5.0);
INSERT INTO RealValues ('Task Identity',16,2.5);
INSERT INTO RealValues ('Feedback from Job',16,4.0);
INSERT INTO RealValues ('Job Complexity',16,2.8);
INSERT INTO RealValues ('Information Processing',16,2.8);
INSERT INTO RealValues ('Problem Solving',16,3.3);
INSERT INTO RealValues ('Skill Variety',16,5.3);
INSERT INTO RealValues ('Specialization',16,3.8);
INSERT INTO RealValues ('Social Support',16,1.2);
INSERT INTO RealValues ('Initiated Interdependence ',16,2.0);
INSERT INTO RealValues ('Received Interdependence',16,3.3);
INSERT INTO RealValues ('Interaction Outside Research Group',16,2.8);
INSERT INTO RealValues ('Feedback from Others',16,1.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',16,1.0);
INSERT INTO RealValues ('Peer Feedback',16,1.0);
INSERT INTO RealValues ('Ergonomics',16,1.7);
INSERT INTO RealValues ('Physical Demands',16,3.3);
INSERT INTO RealValues ('Work Conditions',16,3.0);
INSERT INTO RealValues ('Equipment Use',16,1.0
);
---Profile: 17 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',17,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',17,4.7);
INSERT INTO RealValues ('Work Methods Autonomy',17,3.7);
INSERT INTO RealValues ('Task Variety',17,6.3);
INSERT INTO RealValues ('Task Significance',17,7.0);
INSERT INTO RealValues ('Task Identity',17,4.8);
INSERT INTO RealValues ('Feedback from Job',17,4.0);
INSERT INTO RealValues ('Job Complexity',17,5.8);
INSERT INTO RealValues ('Information Processing',17,4.3);
INSERT INTO RealValues ('Problem Solving',17,6.3);
INSERT INTO RealValues ('Skill Variety',17,5.3);
INSERT INTO RealValues ('Specialization',17,4.8);
INSERT INTO RealValues ('Social Support',17,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',17,4.3);
INSERT INTO RealValues ('Received Interdependence',17,4.3);
INSERT INTO RealValues ('Interaction Outside Research Group',17,5.0);
INSERT INTO RealValues ('Feedback from Others',17,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',17,3.3);
INSERT INTO RealValues ('Peer Feedback',17,2.7);
INSERT INTO RealValues ('Ergonomics',17,4.0);
INSERT INTO RealValues ('Physical Demands',17,6.3);
INSERT INTO RealValues ('Work Conditions',17,5.0);
INSERT INTO RealValues ('Equipment Use',17,3.7
);
---Profile: 18 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',18,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',18,2.0);
INSERT INTO RealValues ('Work Methods Autonomy',18,3.0);
INSERT INTO RealValues ('Task Variety',18,4.0);
INSERT INTO RealValues ('Task Significance',18,4.3);
INSERT INTO RealValues ('Task Identity',18,3.3);
INSERT INTO RealValues ('Feedback from Job',18,2.3);
INSERT INTO RealValues ('Job Complexity',18,2.8);
INSERT INTO RealValues ('Information Processing',18,2.3);
INSERT INTO RealValues ('Problem Solving',18,3.3);
INSERT INTO RealValues ('Skill Variety',18,2.3);
INSERT INTO RealValues ('Specialization',18,2.5);
INSERT INTO RealValues ('Social Support',18,1.2);
INSERT INTO RealValues ('Initiated Interdependence ',18,2.0);
INSERT INTO RealValues ('Received Interdependence',18,3.3);
INSERT INTO RealValues ('Interaction Outside Research Group',18,2.8);
INSERT INTO RealValues ('Feedback from Others',18,1.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',18,1.0);
INSERT INTO RealValues ('Peer Feedback',18,1.0);
INSERT INTO RealValues ('Ergonomics',18,1.7);
INSERT INTO RealValues ('Physical Demands',18,3.3);
INSERT INTO RealValues ('Work Conditions',18,3.0);
INSERT INTO RealValues ('Equipment Use',18,1.0
);
---Profile: 19 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',19,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',19,2.3);
INSERT INTO RealValues ('Work Methods Autonomy',19,2.0);
INSERT INTO RealValues ('Task Variety',19,3.8);
INSERT INTO RealValues ('Task Significance',19,3.5);
INSERT INTO RealValues ('Task Identity',19,4.8);
INSERT INTO RealValues ('Feedback from Job',19,2.7);
INSERT INTO RealValues ('Job Complexity',19,3.0);
INSERT INTO RealValues ('Information Processing',19,3.0);
INSERT INTO RealValues ('Problem Solving',19,4.0);
INSERT INTO RealValues ('Skill Variety',19,3.5);
INSERT INTO RealValues ('Specialization',19,3.0);
INSERT INTO RealValues ('Social Support',19,1.7);
INSERT INTO RealValues ('Initiated Interdependence ',19,2.0);
INSERT INTO RealValues ('Received Interdependence',19,4.7);
INSERT INTO RealValues ('Interaction Outside Research Group',19,4.0);
INSERT INTO RealValues ('Feedback from Others',19,2.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',19,1.7);
INSERT INTO RealValues ('Peer Feedback',19,1.3);
INSERT INTO RealValues ('Ergonomics',19,2.0);
INSERT INTO RealValues ('Physical Demands',19,4.0);
INSERT INTO RealValues ('Work Conditions',19,3.6);
INSERT INTO RealValues ('Equipment Use',19,4.3
);
---Profile: 20 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',20,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',20,5.0);
INSERT INTO RealValues ('Work Methods Autonomy',20,2.7);
INSERT INTO RealValues ('Task Variety',20,6.5);
INSERT INTO RealValues ('Task Significance',20,5.8);
INSERT INTO RealValues ('Task Identity',20,5.0);
INSERT INTO RealValues ('Feedback from Job',20,4.3);
INSERT INTO RealValues ('Job Complexity',20,4.8);
INSERT INTO RealValues ('Information Processing',20,2.3);
INSERT INTO RealValues ('Problem Solving',20,5.3);
INSERT INTO RealValues ('Skill Variety',20,3.8);
INSERT INTO RealValues ('Specialization',20,3.8);
INSERT INTO RealValues ('Social Support',20,2.0);
INSERT INTO RealValues ('Initiated Interdependence ',20,4.7);
INSERT INTO RealValues ('Received Interdependence',20,6.0);
INSERT INTO RealValues ('Interaction Outside Research Group',20,5.0);
INSERT INTO RealValues ('Feedback from Others',20,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',20,2.0);
INSERT INTO RealValues ('Peer Feedback',20,2.3);
INSERT INTO RealValues ('Ergonomics',20,4.7);
INSERT INTO RealValues ('Physical Demands',20,5.3);
INSERT INTO RealValues ('Work Conditions',20,5.0);
INSERT INTO RealValues ('Equipment Use',20,4.3
);
---Profile: 21 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',21,2.7);
INSERT INTO RealValues ('Decision Making Autonomy',21,4.3);
INSERT INTO RealValues ('Work Methods Autonomy',21,4.3);
INSERT INTO RealValues ('Task Variety',21,6.8);
INSERT INTO RealValues ('Task Significance',21,6.5);
INSERT INTO RealValues ('Task Identity',21,5.3);
INSERT INTO RealValues ('Feedback from Job',21,4.7);
INSERT INTO RealValues ('Job Complexity',21,4.3);
INSERT INTO RealValues ('Information Processing',21,3.8);
INSERT INTO RealValues ('Problem Solving',21,3.8);
INSERT INTO RealValues ('Skill Variety',21,4.5);
INSERT INTO RealValues ('Specialization',21,3.3);
INSERT INTO RealValues ('Social Support',21,3.0);
INSERT INTO RealValues ('Initiated Interdependence ',21,4.3);
INSERT INTO RealValues ('Received Interdependence',21,6.7);
INSERT INTO RealValues ('Interaction Outside Research Group',21,5.5);
INSERT INTO RealValues ('Feedback from Others',21,3.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',21,3.7);
INSERT INTO RealValues ('Peer Feedback',21,4.3);
INSERT INTO RealValues ('Ergonomics',21,4.0);
INSERT INTO RealValues ('Physical Demands',21,6.0);
INSERT INTO RealValues ('Work Conditions',21,4.8);
INSERT INTO RealValues ('Equipment Use',21,4.7
);
---Profile: 22 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',22,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',22,1.3);
INSERT INTO RealValues ('Work Methods Autonomy',22,4.0);
INSERT INTO RealValues ('Task Variety',22,3.8);
INSERT INTO RealValues ('Task Significance',22,5.0);
INSERT INTO RealValues ('Task Identity',22,3.5);
INSERT INTO RealValues ('Feedback from Job',22,2.0);
INSERT INTO RealValues ('Job Complexity',22,2.3);
INSERT INTO RealValues ('Information Processing',22,1.8);
INSERT INTO RealValues ('Problem Solving',22,0.3);
INSERT INTO RealValues ('Skill Variety',22,2.0);
INSERT INTO RealValues ('Specialization',22,1.8);
INSERT INTO RealValues ('Social Support',22,2.0);
INSERT INTO RealValues ('Initiated Interdependence ',22,2.7);
INSERT INTO RealValues ('Received Interdependence',22,3.7);
INSERT INTO RealValues ('Interaction Outside Research Group',22,4.3);
INSERT INTO RealValues ('Feedback from Others',22,0.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',22,2.0);
INSERT INTO RealValues ('Peer Feedback',22,2.7);
INSERT INTO RealValues ('Ergonomics',22,1.7);
INSERT INTO RealValues ('Physical Demands',22,3.0);
INSERT INTO RealValues ('Work Conditions',22,3.0);
INSERT INTO RealValues ('Equipment Use',22,3.0
);
---Profile: 23 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',23,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',23,5.0);
INSERT INTO RealValues ('Work Methods Autonomy',23,2.7);
INSERT INTO RealValues ('Task Variety',23,6.5);
INSERT INTO RealValues ('Task Significance',23,5.8);
INSERT INTO RealValues ('Task Identity',23,4.5);
INSERT INTO RealValues ('Feedback from Job',23,5.0);
INSERT INTO RealValues ('Job Complexity',23,4.8);
INSERT INTO RealValues ('Information Processing',23,2.3);
INSERT INTO RealValues ('Problem Solving',23,5.3);
INSERT INTO RealValues ('Skill Variety',23,3.8);
INSERT INTO RealValues ('Specialization',23,3.8);
INSERT INTO RealValues ('Social Support',23,2.0);
INSERT INTO RealValues ('Initiated Interdependence ',23,4.7);
INSERT INTO RealValues ('Received Interdependence',23,6.0);
INSERT INTO RealValues ('Interaction Outside Research Group',23,5.0);
INSERT INTO RealValues ('Feedback from Others',23,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',23,2.0);
INSERT INTO RealValues ('Peer Feedback',23,2.3);
INSERT INTO RealValues ('Ergonomics',23,4.7);
INSERT INTO RealValues ('Physical Demands',23,5.3);
INSERT INTO RealValues ('Work Conditions',23,5.4);
INSERT INTO RealValues ('Equipment Use',23,2.7
);
---Profile: 24 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',24,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',24,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',24,3.7);
INSERT INTO RealValues ('Task Variety',24,5.8);
INSERT INTO RealValues ('Task Significance',24,5.3);
INSERT INTO RealValues ('Task Identity',24,4.3);
INSERT INTO RealValues ('Feedback from Job',24,5.0);
INSERT INTO RealValues ('Job Complexity',24,4.8);
INSERT INTO RealValues ('Information Processing',24,3.8);
INSERT INTO RealValues ('Problem Solving',24,5.0);
INSERT INTO RealValues ('Skill Variety',24,4.0);
INSERT INTO RealValues ('Specialization',24,4.3);
INSERT INTO RealValues ('Social Support',24,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',24,3.3);
INSERT INTO RealValues ('Received Interdependence',24,5.3);
INSERT INTO RealValues ('Interaction Outside Research Group',24,5.0);
INSERT INTO RealValues ('Feedback from Others',24,3.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',24,2.7);
INSERT INTO RealValues ('Peer Feedback',24,2.3);
INSERT INTO RealValues ('Ergonomics',24,3.0);
INSERT INTO RealValues ('Physical Demands',24,5.0);
INSERT INTO RealValues ('Work Conditions',24,4.6);
INSERT INTO RealValues ('Equipment Use',24,3.3
);
---Profile: 25 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',25,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',25,4.7);
INSERT INTO RealValues ('Work Methods Autonomy',25,3.7);
INSERT INTO RealValues ('Task Variety',25,6.3);
INSERT INTO RealValues ('Task Significance',25,5.8);
INSERT INTO RealValues ('Task Identity',25,4.3);
INSERT INTO RealValues ('Feedback from Job',25,5.7);
INSERT INTO RealValues ('Job Complexity',25,5.5);
INSERT INTO RealValues ('Information Processing',25,4.3);
INSERT INTO RealValues ('Problem Solving',25,5.3);
INSERT INTO RealValues ('Skill Variety',25,4.5);
INSERT INTO RealValues ('Specialization',25,5.5);
INSERT INTO RealValues ('Social Support',25,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',25,5.0);
INSERT INTO RealValues ('Received Interdependence',25,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',25,5.3);
INSERT INTO RealValues ('Feedback from Others',25,4.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',25,3.3);
INSERT INTO RealValues ('Peer Feedback',25,3.0);
INSERT INTO RealValues ('Ergonomics',25,3.7);
INSERT INTO RealValues ('Physical Demands',25,5.7);
INSERT INTO RealValues ('Work Conditions',25,6.2);
INSERT INTO RealValues ('Equipment Use',25,4.0
);
---Profile: 26 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',26,1.7);
INSERT INTO RealValues ('Decision Making Autonomy',26,2.0);
INSERT INTO RealValues ('Work Methods Autonomy',26,2.3);
INSERT INTO RealValues ('Task Variety',26,5.3);
INSERT INTO RealValues ('Task Significance',26,3.8);
INSERT INTO RealValues ('Task Identity',26,3.5);
INSERT INTO RealValues ('Feedback from Job',26,2.7);
INSERT INTO RealValues ('Job Complexity',26,4.3);
INSERT INTO RealValues ('Information Processing',26,2.8);
INSERT INTO RealValues ('Problem Solving',26,4.0);
INSERT INTO RealValues ('Skill Variety',26,3.0);
INSERT INTO RealValues ('Specialization',26,3.3);
INSERT INTO RealValues ('Social Support',26,2.0);
INSERT INTO RealValues ('Initiated Interdependence ',26,2.7);
INSERT INTO RealValues ('Received Interdependence',26,5.0);
INSERT INTO RealValues ('Interaction Outside Research Group',26,4.5);
INSERT INTO RealValues ('Feedback from Others',26,2.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',26,2.0);
INSERT INTO RealValues ('Peer Feedback',26,1.7);
INSERT INTO RealValues ('Ergonomics',26,2.3);
INSERT INTO RealValues ('Physical Demands',26,3.3);
INSERT INTO RealValues ('Work Conditions',26,4.2);
INSERT INTO RealValues ('Equipment Use',26,2.3
);
---Profile: 27 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',27,4.0);
INSERT INTO RealValues ('Decision Making Autonomy',27,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',27,4.0);
INSERT INTO RealValues ('Task Variety',27,6.5);
INSERT INTO RealValues ('Task Significance',27,6.3);
INSERT INTO RealValues ('Task Identity',27,4.8);
INSERT INTO RealValues ('Feedback from Job',27,4.7);
INSERT INTO RealValues ('Job Complexity',27,6.3);
INSERT INTO RealValues ('Information Processing',27,4.8);
INSERT INTO RealValues ('Problem Solving',27,5.3);
INSERT INTO RealValues ('Skill Variety',27,4.5);
INSERT INTO RealValues ('Specialization',27,4.0);
INSERT INTO RealValues ('Social Support',27,3.7);
INSERT INTO RealValues ('Initiated Interdependence ',27,4.3);
INSERT INTO RealValues ('Received Interdependence',27,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',27,5.8);
INSERT INTO RealValues ('Feedback from Others',27,4.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',27,5.3);
INSERT INTO RealValues ('Peer Feedback',27,3.3);
INSERT INTO RealValues ('Ergonomics',27,3.0);
INSERT INTO RealValues ('Physical Demands',27,5.7);
INSERT INTO RealValues ('Work Conditions',27,5.2);
INSERT INTO RealValues ('Equipment Use',27,4.0
);
---Profile: 28 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',28,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',28,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',28,2.7);
INSERT INTO RealValues ('Task Variety',28,5.8);
INSERT INTO RealValues ('Task Significance',28,5.8);
INSERT INTO RealValues ('Task Identity',28,4.0);
INSERT INTO RealValues ('Feedback from Job',28,4.3);
INSERT INTO RealValues ('Job Complexity',28,5.3);
INSERT INTO RealValues ('Information Processing',28,3.8);
INSERT INTO RealValues ('Problem Solving',28,4.5);
INSERT INTO RealValues ('Skill Variety',28,3.5);
INSERT INTO RealValues ('Specialization',28,3.5);
INSERT INTO RealValues ('Social Support',28,3.2);
INSERT INTO RealValues ('Initiated Interdependence ',28,4.3);
INSERT INTO RealValues ('Received Interdependence',28,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',28,5.0);
INSERT INTO RealValues ('Feedback from Others',28,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',28,2.0);
INSERT INTO RealValues ('Peer Feedback',28,1.3);
INSERT INTO RealValues ('Ergonomics',28,3.0);
INSERT INTO RealValues ('Physical Demands',28,6.0);
INSERT INTO RealValues ('Work Conditions',28,4.8);
INSERT INTO RealValues ('Equipment Use',28,3.0
);
---Profile: 29 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',29,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',29,3.7);
INSERT INTO RealValues ('Work Methods Autonomy',29,4.7);
INSERT INTO RealValues ('Task Variety',29,5.5);
INSERT INTO RealValues ('Task Significance',29,6.5);
INSERT INTO RealValues ('Task Identity',29,5.0);
INSERT INTO RealValues ('Feedback from Job',29,4.7);
INSERT INTO RealValues ('Job Complexity',29,5.5);
INSERT INTO RealValues ('Information Processing',29,5.8);
INSERT INTO RealValues ('Problem Solving',29,4.3);
INSERT INTO RealValues ('Skill Variety',29,4.0);
INSERT INTO RealValues ('Specialization',29,4.3);
INSERT INTO RealValues ('Social Support',29,2.7);
INSERT INTO RealValues ('Initiated Interdependence ',29,4.0);
INSERT INTO RealValues ('Received Interdependence',29,7.0);
INSERT INTO RealValues ('Interaction Outside Research Group',29,5.5);
INSERT INTO RealValues ('Feedback from Others',29,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',29,3.0);
INSERT INTO RealValues ('Peer Feedback',29,2.3);
INSERT INTO RealValues ('Ergonomics',29,3.7);
INSERT INTO RealValues ('Physical Demands',29,6.0);
INSERT INTO RealValues ('Work Conditions',29,5.8);
INSERT INTO RealValues ('Equipment Use',29,3.3
);
---Profile: 30 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',30,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',30,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',30,2.7);
INSERT INTO RealValues ('Task Variety',30,4.0);
INSERT INTO RealValues ('Task Significance',30,3.5);
INSERT INTO RealValues ('Task Identity',30,2.3);
INSERT INTO RealValues ('Feedback from Job',30,2.7);
INSERT INTO RealValues ('Job Complexity',30,3.3);
INSERT INTO RealValues ('Information Processing',30,3.3);
INSERT INTO RealValues ('Problem Solving',30,3.0);
INSERT INTO RealValues ('Skill Variety',30,2.8);
INSERT INTO RealValues ('Specialization',30,3.0);
INSERT INTO RealValues ('Social Support',30,2.3);
INSERT INTO RealValues ('Initiated Interdependence ',30,2.3);
INSERT INTO RealValues ('Received Interdependence',30,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',30,3.0);
INSERT INTO RealValues ('Feedback from Others',30,1.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',30,2.0);
INSERT INTO RealValues ('Peer Feedback',30,1.0);
INSERT INTO RealValues ('Ergonomics',30,4.3);
INSERT INTO RealValues ('Physical Demands',30,3.3);
INSERT INTO RealValues ('Work Conditions',30,3.2);
INSERT INTO RealValues ('Equipment Use',30,2.0
);
---Profile: 31 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',31,2.7);
INSERT INTO RealValues ('Decision Making Autonomy',31,4.0);
INSERT INTO RealValues ('Work Methods Autonomy',31,5.7);
INSERT INTO RealValues ('Task Variety',31,6.5);
INSERT INTO RealValues ('Task Significance',31,5.8);
INSERT INTO RealValues ('Task Identity',31,5.3);
INSERT INTO RealValues ('Feedback from Job',31,3.7);
INSERT INTO RealValues ('Job Complexity',31,5.3);
INSERT INTO RealValues ('Information Processing',31,5.5);
INSERT INTO RealValues ('Problem Solving',31,5.0);
INSERT INTO RealValues ('Skill Variety',31,3.8);
INSERT INTO RealValues ('Specialization',31,4.3);
INSERT INTO RealValues ('Social Support',31,3.7);
INSERT INTO RealValues ('Initiated Interdependence ',31,4.0);
INSERT INTO RealValues ('Received Interdependence',31,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',31,5.0);
INSERT INTO RealValues ('Feedback from Others',31,4.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',31,6.0);
INSERT INTO RealValues ('Peer Feedback',31,2.3);
INSERT INTO RealValues ('Ergonomics',31,5.0);
INSERT INTO RealValues ('Physical Demands',31,5.7);
INSERT INTO RealValues ('Work Conditions',31,4.4);
INSERT INTO RealValues ('Equipment Use',31,3.0
);
---Profile: 32 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',32,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',32,5.3);
INSERT INTO RealValues ('Work Methods Autonomy',32,5.3);
INSERT INTO RealValues ('Task Variety',32,6.3);
INSERT INTO RealValues ('Task Significance',32,4.3);
INSERT INTO RealValues ('Task Identity',32,3.8);
INSERT INTO RealValues ('Feedback from Job',32,4.0);
INSERT INTO RealValues ('Job Complexity',32,4.8);
INSERT INTO RealValues ('Information Processing',32,3.3);
INSERT INTO RealValues ('Problem Solving',32,5.0);
INSERT INTO RealValues ('Skill Variety',32,3.0);
INSERT INTO RealValues ('Specialization',32,3.5);
INSERT INTO RealValues ('Social Support',32,1.7);
INSERT INTO RealValues ('Initiated Interdependence ',32,2.3);
INSERT INTO RealValues ('Received Interdependence',32,5.7);
INSERT INTO RealValues ('Interaction Outside Research Group',32,4.3);
INSERT INTO RealValues ('Feedback from Others',32,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',32,2.0);
INSERT INTO RealValues ('Peer Feedback',32,2.3);
INSERT INTO RealValues ('Ergonomics',32,5.0);
INSERT INTO RealValues ('Physical Demands',32,5.7);
INSERT INTO RealValues ('Work Conditions',32,4.4);
INSERT INTO RealValues ('Equipment Use',32,2.7
);
---Profile: 33 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',33,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',33,5.3);
INSERT INTO RealValues ('Work Methods Autonomy',33,4.3);
INSERT INTO RealValues ('Task Variety',33,7.0);
INSERT INTO RealValues ('Task Significance',33,3.5);
INSERT INTO RealValues ('Task Identity',33,4.8);
INSERT INTO RealValues ('Feedback from Job',33,5.0);
INSERT INTO RealValues ('Job Complexity',33,5.8);
INSERT INTO RealValues ('Information Processing',33,3.5);
INSERT INTO RealValues ('Problem Solving',33,5.0);
INSERT INTO RealValues ('Skill Variety',33,5.0);
INSERT INTO RealValues ('Specialization',33,4.0);
INSERT INTO RealValues ('Social Support',33,2.2);
INSERT INTO RealValues ('Initiated Interdependence ',33,2.7);
INSERT INTO RealValues ('Received Interdependence',33,6.0);
INSERT INTO RealValues ('Interaction Outside Research Group',33,5.0);
INSERT INTO RealValues ('Feedback from Others',33,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',33,3.3);
INSERT INTO RealValues ('Peer Feedback',33,4.3);
INSERT INTO RealValues ('Ergonomics',33,4.0);
INSERT INTO RealValues ('Physical Demands',33,6.3);
INSERT INTO RealValues ('Work Conditions',33,4.2);
INSERT INTO RealValues ('Equipment Use',33,3.7
);
---Profile: 34 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',34,1.0);
INSERT INTO RealValues ('Decision Making Autonomy',34,1.7);
INSERT INTO RealValues ('Work Methods Autonomy',34,3.0);
INSERT INTO RealValues ('Task Variety',34,3.5);
INSERT INTO RealValues ('Task Significance',34,4.0);
INSERT INTO RealValues ('Task Identity',34,2.5);
INSERT INTO RealValues ('Feedback from Job',34,2.0);
INSERT INTO RealValues ('Job Complexity',34,2.8);
INSERT INTO RealValues ('Information Processing',34,1.8);
INSERT INTO RealValues ('Problem Solving',34,4.0);
INSERT INTO RealValues ('Skill Variety',34,2.8);
INSERT INTO RealValues ('Specialization',34,2.5);
INSERT INTO RealValues ('Social Support',34,1.3);
INSERT INTO RealValues ('Initiated Interdependence ',34,2.7);
INSERT INTO RealValues ('Received Interdependence',34,3.0);
INSERT INTO RealValues ('Interaction Outside Research Group',34,2.8);
INSERT INTO RealValues ('Feedback from Others',34,1.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',34,1.0);
INSERT INTO RealValues ('Peer Feedback',34,3.0);
INSERT INTO RealValues ('Ergonomics',34,1.7);
INSERT INTO RealValues ('Physical Demands',34,3.3);
INSERT INTO RealValues ('Work Conditions',34,2.8);
INSERT INTO RealValues ('Equipment Use',34,2.0
);
---Profile: 35 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',35,3.7);
INSERT INTO RealValues ('Decision Making Autonomy',35,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',35,5.7);
INSERT INTO RealValues ('Task Variety',35,5.3);
INSERT INTO RealValues ('Task Significance',35,5.0);
INSERT INTO RealValues ('Task Identity',35,4.8);
INSERT INTO RealValues ('Feedback from Job',35,4.7);
INSERT INTO RealValues ('Job Complexity',35,4.8);
INSERT INTO RealValues ('Information Processing',35,4.3);
INSERT INTO RealValues ('Problem Solving',35,5.8);
INSERT INTO RealValues ('Skill Variety',35,4.8);
INSERT INTO RealValues ('Specialization',35,4.8);
INSERT INTO RealValues ('Social Support',35,3.8);
INSERT INTO RealValues ('Initiated Interdependence ',35,4.3);
INSERT INTO RealValues ('Received Interdependence',35,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',35,5.8);
INSERT INTO RealValues ('Feedback from Others',35,4.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',35,5.3);
INSERT INTO RealValues ('Peer Feedback',35,5.0);
INSERT INTO RealValues ('Ergonomics',35,3.0);
INSERT INTO RealValues ('Physical Demands',35,3.7);
INSERT INTO RealValues ('Work Conditions',35,4.6);
INSERT INTO RealValues ('Equipment Use',35,6.0
);
---Profile: 36 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',36,1.7);
INSERT INTO RealValues ('Decision Making Autonomy',36,2.7);
INSERT INTO RealValues ('Work Methods Autonomy',36,4.0);
INSERT INTO RealValues ('Task Variety',36,5.3);
INSERT INTO RealValues ('Task Significance',36,5.0);
INSERT INTO RealValues ('Task Identity',36,4.0);
INSERT INTO RealValues ('Feedback from Job',36,4.3);
INSERT INTO RealValues ('Job Complexity',36,4.0);
INSERT INTO RealValues ('Information Processing',36,3.3);
INSERT INTO RealValues ('Problem Solving',36,5.3);
INSERT INTO RealValues ('Skill Variety',36,4.3);
INSERT INTO RealValues ('Specialization',36,4.3);
INSERT INTO RealValues ('Social Support',36,2.3);
INSERT INTO RealValues ('Initiated Interdependence ',36,4.3);
INSERT INTO RealValues ('Received Interdependence',36,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',36,5.0);
INSERT INTO RealValues ('Feedback from Others',36,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',36,2.0);
INSERT INTO RealValues ('Peer Feedback',36,3.0);
INSERT INTO RealValues ('Ergonomics',36,3.0);
INSERT INTO RealValues ('Physical Demands',36,2.7);
INSERT INTO RealValues ('Work Conditions',36,3.8);
INSERT INTO RealValues ('Equipment Use',36,3.0
);
---Profile: 37 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',37,1.7);
INSERT INTO RealValues ('Decision Making Autonomy',37,3.7);
INSERT INTO RealValues ('Work Methods Autonomy',37,4.7);
INSERT INTO RealValues ('Task Variety',37,5.0);
INSERT INTO RealValues ('Task Significance',37,6.5);
INSERT INTO RealValues ('Task Identity',37,4.0);
INSERT INTO RealValues ('Feedback from Job',37,4.7);
INSERT INTO RealValues ('Job Complexity',37,3.5);
INSERT INTO RealValues ('Information Processing',37,4.8);
INSERT INTO RealValues ('Problem Solving',37,4.5);
INSERT INTO RealValues ('Skill Variety',37,5.3);
INSERT INTO RealValues ('Specialization',37,5.3);
INSERT INTO RealValues ('Social Support',37,2.7);
INSERT INTO RealValues ('Initiated Interdependence ',37,4.0);
INSERT INTO RealValues ('Received Interdependence',37,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',37,4.0);
INSERT INTO RealValues ('Feedback from Others',37,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',37,4.3);
INSERT INTO RealValues ('Peer Feedback',37,2.3);
INSERT INTO RealValues ('Ergonomics',37,3.7);
INSERT INTO RealValues ('Physical Demands',37,4.3);
INSERT INTO RealValues ('Work Conditions',37,4.0);
INSERT INTO RealValues ('Equipment Use',37,5.0
);
---Profile: 38 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',38,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',38,3.3);
INSERT INTO RealValues ('Work Methods Autonomy',38,3.3);
INSERT INTO RealValues ('Task Variety',38,5.5);
INSERT INTO RealValues ('Task Significance',38,3.5);
INSERT INTO RealValues ('Task Identity',38,2.3);
INSERT INTO RealValues ('Feedback from Job',38,2.7);
INSERT INTO RealValues ('Job Complexity',38,2.0);
INSERT INTO RealValues ('Information Processing',38,1.8);
INSERT INTO RealValues ('Problem Solving',38,4.0);
INSERT INTO RealValues ('Skill Variety',38,3.8);
INSERT INTO RealValues ('Specialization',38,2.3);
INSERT INTO RealValues ('Social Support',38,2.0);
INSERT INTO RealValues ('Initiated Interdependence ',38,2.3);
INSERT INTO RealValues ('Received Interdependence',38,4.0);
INSERT INTO RealValues ('Interaction Outside Research Group',38,2.3);
INSERT INTO RealValues ('Feedback from Others',38,1.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',38,3.0);
INSERT INTO RealValues ('Peer Feedback',38,1.0);
INSERT INTO RealValues ('Ergonomics',38,3.0);
INSERT INTO RealValues ('Physical Demands',38,2.3);
INSERT INTO RealValues ('Work Conditions',38,2.4);
INSERT INTO RealValues ('Equipment Use',38,3.0
);
---Profile: 39 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',39,2.7);
INSERT INTO RealValues ('Decision Making Autonomy',39,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',39,3.7);
INSERT INTO RealValues ('Task Variety',39,6.3);
INSERT INTO RealValues ('Task Significance',39,5.8);
INSERT INTO RealValues ('Task Identity',39,4.0);
INSERT INTO RealValues ('Feedback from Job',39,3.3);
INSERT INTO RealValues ('Job Complexity',39,5.0);
INSERT INTO RealValues ('Information Processing',39,4.3);
INSERT INTO RealValues ('Problem Solving',39,5.5);
INSERT INTO RealValues ('Skill Variety',39,6.0);
INSERT INTO RealValues ('Specialization',39,5.3);
INSERT INTO RealValues ('Social Support',39,2.7);
INSERT INTO RealValues ('Initiated Interdependence ',39,2.3);
INSERT INTO RealValues ('Received Interdependence',39,4.3);
INSERT INTO RealValues ('Interaction Outside Research Group',39,4.5);
INSERT INTO RealValues ('Feedback from Others',39,3.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',39,7.0);
INSERT INTO RealValues ('Peer Feedback',39,1.7);
INSERT INTO RealValues ('Ergonomics',39,3.7);
INSERT INTO RealValues ('Physical Demands',39,4.7);
INSERT INTO RealValues ('Work Conditions',39,4.2);
INSERT INTO RealValues ('Equipment Use',39,3.0
);
---Profile: 40 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',40,3.3);
INSERT INTO RealValues ('Decision Making Autonomy',40,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',40,4.7);
INSERT INTO RealValues ('Task Variety',40,4.5);
INSERT INTO RealValues ('Task Significance',40,5.3);
INSERT INTO RealValues ('Task Identity',40,4.0);
INSERT INTO RealValues ('Feedback from Job',40,3.7);
INSERT INTO RealValues ('Job Complexity',40,3.8);
INSERT INTO RealValues ('Information Processing',40,3.5);
INSERT INTO RealValues ('Problem Solving',40,5.0);
INSERT INTO RealValues ('Skill Variety',40,5.3);
INSERT INTO RealValues ('Specialization',40,4.8);
INSERT INTO RealValues ('Social Support',40,2.2);
INSERT INTO RealValues ('Initiated Interdependence ',40,3.0);
INSERT INTO RealValues ('Received Interdependence',40,5.7);
INSERT INTO RealValues ('Interaction Outside Research Group',40,3.8);
INSERT INTO RealValues ('Feedback from Others',40,1.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',40,3.7);
INSERT INTO RealValues ('Peer Feedback',40,1.7);
INSERT INTO RealValues ('Ergonomics',40,2.7);
INSERT INTO RealValues ('Physical Demands',40,5.7);
INSERT INTO RealValues ('Work Conditions',40,4.4);
INSERT INTO RealValues ('Equipment Use',40,2.7
);
---Profile: 41 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',41,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',41,2.0);
INSERT INTO RealValues ('Work Methods Autonomy',41,4.7);
INSERT INTO RealValues ('Task Variety',41,6.0);
INSERT INTO RealValues ('Task Significance',41,6.3);
INSERT INTO RealValues ('Task Identity',41,5.3);
INSERT INTO RealValues ('Feedback from Job',41,2.0);
INSERT INTO RealValues ('Job Complexity',41,4.3);
INSERT INTO RealValues ('Information Processing',41,3.8);
INSERT INTO RealValues ('Problem Solving',41,5.5);
INSERT INTO RealValues ('Skill Variety',41,5.3);
INSERT INTO RealValues ('Specialization',41,6.0);
INSERT INTO RealValues ('Social Support',41,2.8);
INSERT INTO RealValues ('Initiated Interdependence ',41,3.3);
INSERT INTO RealValues ('Received Interdependence',41,4.3);
INSERT INTO RealValues ('Interaction Outside Research Group',41,4.3);
INSERT INTO RealValues ('Feedback from Others',41,5.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',41,2.0);
INSERT INTO RealValues ('Peer Feedback',41,2.0);
INSERT INTO RealValues ('Ergonomics',41,4.3);
INSERT INTO RealValues ('Physical Demands',41,6.3);
INSERT INTO RealValues ('Work Conditions',41,5.0);
INSERT INTO RealValues ('Equipment Use',41,3.7
);
---Profile: 42 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',42,1.0);
INSERT INTO RealValues ('Decision Making Autonomy',42,2.0);
INSERT INTO RealValues ('Work Methods Autonomy',42,4.0);
INSERT INTO RealValues ('Task Variety',42,3.8);
INSERT INTO RealValues ('Task Significance',42,5.0);
INSERT INTO RealValues ('Task Identity',42,2.8);
INSERT INTO RealValues ('Feedback from Job',42,3.0);
INSERT INTO RealValues ('Job Complexity',42,2.8);
INSERT INTO RealValues ('Information Processing',42,3.3);
INSERT INTO RealValues ('Problem Solving',42,3.3);
INSERT INTO RealValues ('Skill Variety',42,5.3);
INSERT INTO RealValues ('Specialization',42,4.0);
INSERT INTO RealValues ('Social Support',42,1.2);
INSERT INTO RealValues ('Initiated Interdependence ',42,1.7);
INSERT INTO RealValues ('Received Interdependence',42,3.3);
INSERT INTO RealValues ('Interaction Outside Research Group',42,2.8);
INSERT INTO RealValues ('Feedback from Others',42,3.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',42,1.0);
INSERT INTO RealValues ('Peer Feedback',42,2.3);
INSERT INTO RealValues ('Ergonomics',42,1.7);
INSERT INTO RealValues ('Physical Demands',42,3.3);
INSERT INTO RealValues ('Work Conditions',42,3.0);
INSERT INTO RealValues ('Equipment Use',42,1.0
);
---Profile: 43 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',43,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',43,4.7);
INSERT INTO RealValues ('Work Methods Autonomy',43,3.0);
INSERT INTO RealValues ('Task Variety',43,6.3);
INSERT INTO RealValues ('Task Significance',43,5.3);
INSERT INTO RealValues ('Task Identity',43,3.8);
INSERT INTO RealValues ('Feedback from Job',43,4.0);
INSERT INTO RealValues ('Job Complexity',43,5.8);
INSERT INTO RealValues ('Information Processing',43,4.3);
INSERT INTO RealValues ('Problem Solving',43,6.3);
INSERT INTO RealValues ('Skill Variety',43,5.3);
INSERT INTO RealValues ('Specialization',43,5.5);
INSERT INTO RealValues ('Social Support',43,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',43,4.3);
INSERT INTO RealValues ('Received Interdependence',43,4.3);
INSERT INTO RealValues ('Interaction Outside Research Group',43,5.5);
INSERT INTO RealValues ('Feedback from Others',43,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',43,3.3);
INSERT INTO RealValues ('Peer Feedback',43,2.3);
INSERT INTO RealValues ('Ergonomics',43,4.0);
INSERT INTO RealValues ('Physical Demands',43,5.3);
INSERT INTO RealValues ('Work Conditions',43,4.6);
INSERT INTO RealValues ('Equipment Use',43,3.7
);
---Profile: 44 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',44,3.0);
INSERT INTO RealValues ('Decision Making Autonomy',44,2.0);
INSERT INTO RealValues ('Work Methods Autonomy',44,3.0);
INSERT INTO RealValues ('Task Variety',44,3.3);
INSERT INTO RealValues ('Task Significance',44,4.3);
INSERT INTO RealValues ('Task Identity',44,2.3);
INSERT INTO RealValues ('Feedback from Job',44,2.3);
INSERT INTO RealValues ('Job Complexity',44,2.8);
INSERT INTO RealValues ('Information Processing',44,2.8);
INSERT INTO RealValues ('Problem Solving',44,3.3);
INSERT INTO RealValues ('Skill Variety',44,2.3);
INSERT INTO RealValues ('Specialization',44,3.3);
INSERT INTO RealValues ('Social Support',44,1.2);
INSERT INTO RealValues ('Initiated Interdependence ',44,2.0);
INSERT INTO RealValues ('Received Interdependence',44,3.3);
INSERT INTO RealValues ('Interaction Outside Research Group',44,3.8);
INSERT INTO RealValues ('Feedback from Others',44,2.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',44,1.7);
INSERT INTO RealValues ('Peer Feedback',44,1.0);
INSERT INTO RealValues ('Ergonomics',44,1.7);
INSERT INTO RealValues ('Physical Demands',44,3.3);
INSERT INTO RealValues ('Work Conditions',44,2.8);
INSERT INTO RealValues ('Equipment Use',44,1.0
);
---Profile: 45 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',45,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',45,2.3);
INSERT INTO RealValues ('Work Methods Autonomy',45,2.0);
INSERT INTO RealValues ('Task Variety',45,2.5);
INSERT INTO RealValues ('Task Significance',45,4.0);
INSERT INTO RealValues ('Task Identity',45,3.5);
INSERT INTO RealValues ('Feedback from Job',45,2.7);
INSERT INTO RealValues ('Job Complexity',45,3.3);
INSERT INTO RealValues ('Information Processing',45,3.5);
INSERT INTO RealValues ('Problem Solving',45,4.0);
INSERT INTO RealValues ('Skill Variety',45,3.5);
INSERT INTO RealValues ('Specialization',45,4.5);
INSERT INTO RealValues ('Social Support',45,2.2);
INSERT INTO RealValues ('Initiated Interdependence ',45,2.0);
INSERT INTO RealValues ('Received Interdependence',45,3.0);
INSERT INTO RealValues ('Interaction Outside Research Group',45,4.8);
INSERT INTO RealValues ('Feedback from Others',45,2.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',45,2.3);
INSERT INTO RealValues ('Peer Feedback',45,1.3);
INSERT INTO RealValues ('Ergonomics',45,2.0);
INSERT INTO RealValues ('Physical Demands',45,4.0);
INSERT INTO RealValues ('Work Conditions',45,3.0);
INSERT INTO RealValues ('Equipment Use',45,2.3
);
---Profile: 46 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',46,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',46,5.0);
INSERT INTO RealValues ('Work Methods Autonomy',46,2.7);
INSERT INTO RealValues ('Task Variety',46,5.3);
INSERT INTO RealValues ('Task Significance',46,5.3);
INSERT INTO RealValues ('Task Identity',46,3.5);
INSERT INTO RealValues ('Feedback from Job',46,4.3);
INSERT INTO RealValues ('Job Complexity',46,4.5);
INSERT INTO RealValues ('Information Processing',46,2.3);
INSERT INTO RealValues ('Problem Solving',46,5.3);
INSERT INTO RealValues ('Skill Variety',46,3.8);
INSERT INTO RealValues ('Specialization',46,3.8);
INSERT INTO RealValues ('Social Support',46,3.0);
INSERT INTO RealValues ('Initiated Interdependence ',46,4.7);
INSERT INTO RealValues ('Received Interdependence',46,4.7);
INSERT INTO RealValues ('Interaction Outside Research Group',46,5.8);
INSERT INTO RealValues ('Feedback from Others',46,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',46,3.7);
INSERT INTO RealValues ('Peer Feedback',46,1.0);
INSERT INTO RealValues ('Ergonomics',46,4.3);
INSERT INTO RealValues ('Physical Demands',46,5.3);
INSERT INTO RealValues ('Work Conditions',46,3.8);
INSERT INTO RealValues ('Equipment Use',46,2.7
);
---Profile: 47 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',47,2.7);
INSERT INTO RealValues ('Decision Making Autonomy',47,4.3);
INSERT INTO RealValues ('Work Methods Autonomy',47,4.3);
INSERT INTO RealValues ('Task Variety',47,5.3);
INSERT INTO RealValues ('Task Significance',47,5.8);
INSERT INTO RealValues ('Task Identity',47,5.3);
INSERT INTO RealValues ('Feedback from Job',47,4.0);
INSERT INTO RealValues ('Job Complexity',47,4.0);
INSERT INTO RealValues ('Information Processing',47,3.8);
INSERT INTO RealValues ('Problem Solving',47,3.8);
INSERT INTO RealValues ('Skill Variety',47,4.5);
INSERT INTO RealValues ('Specialization',47,3.3);
INSERT INTO RealValues ('Social Support',47,3.8);
INSERT INTO RealValues ('Initiated Interdependence ',47,4.3);
INSERT INTO RealValues ('Received Interdependence',47,6.7);
INSERT INTO RealValues ('Interaction Outside Research Group',47,3.8);
INSERT INTO RealValues ('Feedback from Others',47,3.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',47,3.7);
INSERT INTO RealValues ('Peer Feedback',47,3.0);
INSERT INTO RealValues ('Ergonomics',47,3.7);
INSERT INTO RealValues ('Physical Demands',47,6.0);
INSERT INTO RealValues ('Work Conditions',47,4.2);
INSERT INTO RealValues ('Equipment Use',47,3.3
);
---Profile: 48 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',48,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',48,1.3);
INSERT INTO RealValues ('Work Methods Autonomy',48,4.0);
INSERT INTO RealValues ('Task Variety',48,3.0);
INSERT INTO RealValues ('Task Significance',48,4.8);
INSERT INTO RealValues ('Task Identity',48,3.0);
INSERT INTO RealValues ('Feedback from Job',48,2.3);
INSERT INTO RealValues ('Job Complexity',48,3.8);
INSERT INTO RealValues ('Information Processing',48,1.8);
INSERT INTO RealValues ('Problem Solving',48,0.3);
INSERT INTO RealValues ('Skill Variety',48,2.0);
INSERT INTO RealValues ('Specialization',48,1.8);
INSERT INTO RealValues ('Social Support',48,2.5);
INSERT INTO RealValues ('Initiated Interdependence ',48,2.7);
INSERT INTO RealValues ('Received Interdependence',48,4.7);
INSERT INTO RealValues ('Interaction Outside Research Group',48,3.5);
INSERT INTO RealValues ('Feedback from Others',48,1.3);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',48,2.0);
INSERT INTO RealValues ('Peer Feedback',48,3.7);
INSERT INTO RealValues ('Ergonomics',48,1.7);
INSERT INTO RealValues ('Physical Demands',48,2.3);
INSERT INTO RealValues ('Work Conditions',48,3.2);
INSERT INTO RealValues ('Equipment Use',48,3.0
);
---Profile: 49 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',49,2.0);
INSERT INTO RealValues ('Decision Making Autonomy',49,5.0);
INSERT INTO RealValues ('Work Methods Autonomy',49,2.7);
INSERT INTO RealValues ('Task Variety',49,6.5);
INSERT INTO RealValues ('Task Significance',49,3.5);
INSERT INTO RealValues ('Task Identity',49,5.3);
INSERT INTO RealValues ('Feedback from Job',49,4.0);
INSERT INTO RealValues ('Job Complexity',49,4.8);
INSERT INTO RealValues ('Information Processing',49,2.3);
INSERT INTO RealValues ('Problem Solving',49,5.3);
INSERT INTO RealValues ('Skill Variety',49,3.8);
INSERT INTO RealValues ('Specialization',49,3.8);
INSERT INTO RealValues ('Social Support',49,3.0);
INSERT INTO RealValues ('Initiated Interdependence ',49,4.7);
INSERT INTO RealValues ('Received Interdependence',49,6.3);
INSERT INTO RealValues ('Interaction Outside Research Group',49,5.0);
INSERT INTO RealValues ('Feedback from Others',49,2.7);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',49,2.0);
INSERT INTO RealValues ('Peer Feedback',49,3.7);
INSERT INTO RealValues ('Ergonomics',49,3.3);
INSERT INTO RealValues ('Physical Demands',49,4.0);
INSERT INTO RealValues ('Work Conditions',49,5.0);
INSERT INTO RealValues ('Equipment Use',49,2.7
);
---Profile: 50 Real Values---
INSERT INTO RealValues ('Work Scheduling Autonomy',50,2.3);
INSERT INTO RealValues ('Decision Making Autonomy',50,3.0);
INSERT INTO RealValues ('Work Methods Autonomy',50,3.7);
INSERT INTO RealValues ('Task Variety',50,5.8);
INSERT INTO RealValues ('Task Significance',50,3.8);
INSERT INTO RealValues ('Task Identity',50,3.3);
INSERT INTO RealValues ('Feedback from Job',50,5.3);
INSERT INTO RealValues ('Job Complexity',50,4.8);
INSERT INTO RealValues ('Information Processing',50,3.8);
INSERT INTO RealValues ('Problem Solving',50,5.0);
INSERT INTO RealValues ('Skill Variety',50,4.0);
INSERT INTO RealValues ('Specialization',50,4.3);
INSERT INTO RealValues ('Social Support',50,3.5);
INSERT INTO RealValues ('Initiated Interdependence ',50,4.0);
INSERT INTO RealValues ('Received Interdependence',50,5.3);
INSERT INTO RealValues ('Interaction Outside Research Group',50,4.5);
INSERT INTO RealValues ('Feedback from Others',50,3.0);
INSERT INTO RealValues ('Faculty/projecdt leader feedback',50,2.7);
INSERT INTO RealValues ('Peer Feedback',50,2.3);
INSERT INTO RealValues ('Ergonomics',50,2.0);
INSERT INTO RealValues ('Physical Demands',50,4.3);
INSERT INTO RealValues ('Work Conditions',50,4.2);
INSERT INTO RealValues ('Equipment Use',50,3.3);
