
INSERT INTO AnswerOptions values(1,1,1,'Agriculture');
INSERT INTO AnswerOptions values(1,1,2,'Bioinformatics and/or computational biology');
INSERT INTO AnswerOptions values(1,1,3,'Discipline-based education research (DBER)');
INSERT INTO AnswerOptions values(1,1,4,'Engineering');
INSERT INTO AnswerOptions values(1,1,5,'Computer science and computer engineering');
INSERT INTO AnswerOptions values(1,1,6,'Engineering - Biomedical');
INSERT INTO AnswerOptions values(1,1,7,'Engineering (other)');
INSERT INTO AnswerOptions values(1,1,8,'Environmental science');
INSERT INTO AnswerOptions values(1,1,9,'Kinesiology');
INSERT INTO AnswerOptions values(1,1,10,'anatomy and physiology ');
INSERT INTO AnswerOptions values(1,1,11,'biochemistry');
INSERT INTO AnswerOptions values(1,1,12,'general biology');
INSERT INTO AnswerOptions values(1,1,13,'botany');
INSERT INTO AnswerOptions values(1,1,14,'ecology');
INSERT INTO AnswerOptions values(1,1,15,'evolution');
INSERT INTO AnswerOptions values(1,1,16,'genetics ');
INSERT INTO AnswerOptions values(1,1,17,'zoology');
INSERT INTO AnswerOptions values(1,1,18,'Marine science');
INSERT INTO AnswerOptions values(1,1,19,'Mathematics');
INSERT INTO AnswerOptions values(1,1,20,'Neuroscience');
INSERT INTO AnswerOptions values(1,1,21,'Physical Sciences:');
INSERT INTO AnswerOptions values(1,1,22,'Astronomy');
INSERT INTO AnswerOptions values(1,1,23,'Chemistry ');
INSERT INTO AnswerOptions values(1,1,24,'Physics');
INSERT INTO AnswerOptions values(1,1,25,'Geology');
INSERT INTO AnswerOptions values(1,1,26,'Soil science');
INSERT INTO AnswerOptions values(1,1,27,'Statistics and/or Data Science');
INSERT INTO AnswerOptions values(1,1,28,'Other');
INSERT INTO AnswerOptions values(1,1,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,2,1,'1 student');
INSERT INTO AnswerOptions values(1,2,2,'2-4 students');
INSERT INTO AnswerOptions values(1,2,3,'5-8 students');
INSERT INTO AnswerOptions values(1,2,4,'9-12 students');
INSERT INTO AnswerOptions values(1,2,5,'more than 12 students');
INSERT INTO AnswerOptions values(1,2,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,3,1,'2 ');
INSERT INTO AnswerOptions values(1,3,2,'3-5 ');
INSERT INTO AnswerOptions values(1,3,3,'6-9');
INSERT INTO AnswerOptions values(1,3,4,'10-13');
INSERT INTO AnswerOptions values(1,3,5,'More than 13');
INSERT INTO AnswerOptions values(1,3,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,4,1,'Faculty member');
INSERT INTO AnswerOptions values(1,4,2,'Postdoctoral researcher');
INSERT INTO AnswerOptions values(1,4,3,'"Graduate student');
INSERT INTO AnswerOptions values(1,4,4,'Other');
INSERT INTO AnswerOptions values(1,4,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,5,1,'Laboratory research');
INSERT INTO AnswerOptions values(1,5,2,'Field research');
INSERT INTO AnswerOptions values(1,5,3,'Computer-based research');
INSERT INTO AnswerOptions values(1,5,0,'prefer not to say');
INSERT INTO AnswerOptions values(1,6,1,'0 hours a week');
INSERT INTO AnswerOptions values(1,6,2,'1 - 5 hours a week');
INSERT INTO AnswerOptions values(1,6,3,'6 - 10 hours a week');
INSERT INTO AnswerOptions values(1,6,4,'11 - 15 hours a week');
INSERT INTO AnswerOptions values(1,6,5,'16 - 20 hours a week');
INSERT INTO AnswerOptions values(1,6,6,'21 - 25 hours a week');
INSERT INTO AnswerOptions values(1,6,7,'26 - 30 hours a week');
INSERT INTO AnswerOptions values(1,6,8,'more than 30 hours a week');
INSERT INTO AnswerOptions values(1,6,0,'Prefer not to say');
INSERT INTO AnswerOptions values(1,12,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,12,2,' disagree');
INSERT INTO AnswerOptions values(1,12,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,12,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,12,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,12,6,'agree');
INSERT INTO AnswerOptions values(1,12,7,'strongly agree');
INSERT INTO AnswerOptions values(1,12,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,1,1,'Academic (college or university)');
INSERT INTO AnswerOptions values(2,1,2,'Industry - research and development');
INSERT INTO AnswerOptions values(2,1,3,'Industry - production and quality control');
INSERT INTO AnswerOptions values(2,1,4,'Government ');
INSERT INTO AnswerOptions values(2,1,5,'Self-employed consulting/fee for service');
INSERT INTO AnswerOptions values(2,1,6,'Other');
INSERT INTO AnswerOptions values(2,1,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,2,1,'AA - year');
INSERT INTO AnswerOptions values(2,2,2,'Baccalaureate - year');
INSERT INTO AnswerOptions values(2,2,3,'Masters of Science');
INSERT INTO AnswerOptions values(2,2,4,'Ph. D');
INSERT INTO AnswerOptions values(2,2,5,'JD');
INSERT INTO AnswerOptions values(2,2,6,'MD');
INSERT INTO AnswerOptions values(2,2,7,'MBA');
INSERT INTO AnswerOptions values(2,2,8,'not applicable ');
INSERT INTO AnswerOptions values(2,2,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,12,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,12,2,' disagree');
INSERT INTO AnswerOptions values(1,12,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,12,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,12,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,12,6,'agree');
INSERT INTO AnswerOptions values(1,12,7,'strongly agree');
INSERT INTO AnswerOptions values(1,12,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,13,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,13,2,' disagree');
INSERT INTO AnswerOptions values(1,13,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,13,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,13,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,13,6,'agree');
INSERT INTO AnswerOptions values(1,13,7,'strongly agree');
INSERT INTO AnswerOptions values(1,13,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,14,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,14,2,' disagree');
INSERT INTO AnswerOptions values(1,14,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,14,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,14,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,14,6,'agree');
INSERT INTO AnswerOptions values(1,14,7,'strongly agree');
INSERT INTO AnswerOptions values(1,14,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,15,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,15,2,' disagree');
INSERT INTO AnswerOptions values(1,15,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,15,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,15,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,15,6,'agree');
INSERT INTO AnswerOptions values(1,15,7,'strongly agree');
INSERT INTO AnswerOptions values(1,15,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,16,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,16,2,' disagree');
INSERT INTO AnswerOptions values(1,16,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,16,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,16,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,16,6,'agree');
INSERT INTO AnswerOptions values(1,16,7,'strongly agree');
INSERT INTO AnswerOptions values(1,16,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,17,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,17,2,' disagree');
INSERT INTO AnswerOptions values(1,17,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,17,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,17,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,17,6,'agree');
INSERT INTO AnswerOptions values(1,17,7,'strongly agree');
INSERT INTO AnswerOptions values(1,17,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,18,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,18,2,' disagree');
INSERT INTO AnswerOptions values(1,18,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,18,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,18,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,18,6,'agree');
INSERT INTO AnswerOptions values(1,18,7,'strongly agree');
INSERT INTO AnswerOptions values(1,18,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,19,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,19,2,' disagree');
INSERT INTO AnswerOptions values(1,19,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,19,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,19,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,19,6,'agree');
INSERT INTO AnswerOptions values(1,19,7,'strongly agree');
INSERT INTO AnswerOptions values(1,19,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,20,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,20,2,' disagree');
INSERT INTO AnswerOptions values(1,20,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,20,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,20,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,20,6,'agree');
INSERT INTO AnswerOptions values(1,20,7,'strongly agree');
INSERT INTO AnswerOptions values(1,20,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,21,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,21,2,' disagree');
INSERT INTO AnswerOptions values(1,21,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,21,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,21,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,21,6,'agree');
INSERT INTO AnswerOptions values(1,21,7,'strongly agree');
INSERT INTO AnswerOptions values(1,21,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,22,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,22,2,' disagree');
INSERT INTO AnswerOptions values(1,22,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,22,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,22,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,22,6,'agree');
INSERT INTO AnswerOptions values(1,22,7,'strongly agree');
INSERT INTO AnswerOptions values(1,22,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,23,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,23,2,' disagree');
INSERT INTO AnswerOptions values(1,23,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,23,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,23,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,23,6,'agree');
INSERT INTO AnswerOptions values(1,23,7,'strongly agree');
INSERT INTO AnswerOptions values(1,23,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,24,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,24,2,' disagree');
INSERT INTO AnswerOptions values(1,24,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,24,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,24,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,24,6,'agree');
INSERT INTO AnswerOptions values(1,24,7,'strongly agree');
INSERT INTO AnswerOptions values(1,24,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,25,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,25,2,' disagree');
INSERT INTO AnswerOptions values(1,25,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,25,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,25,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,25,6,'agree');
INSERT INTO AnswerOptions values(1,25,7,'strongly agree');
INSERT INTO AnswerOptions values(1,25,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,26,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,26,2,' disagree');
INSERT INTO AnswerOptions values(1,26,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,26,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,26,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,26,6,'agree');
INSERT INTO AnswerOptions values(1,26,7,'strongly agree');
INSERT INTO AnswerOptions values(1,26,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,27,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,27,2,' disagree');
INSERT INTO AnswerOptions values(1,27,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,27,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,27,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,27,6,'agree');
INSERT INTO AnswerOptions values(1,27,7,'strongly agree');
INSERT INTO AnswerOptions values(1,27,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,28,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,28,2,' disagree');
INSERT INTO AnswerOptions values(1,28,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,28,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,28,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,28,6,'agree');
INSERT INTO AnswerOptions values(1,28,7,'strongly agree');
INSERT INTO AnswerOptions values(1,28,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,29,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,29,2,' disagree');
INSERT INTO AnswerOptions values(1,29,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,29,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,29,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,29,6,'agree');
INSERT INTO AnswerOptions values(1,29,7,'strongly agree');
INSERT INTO AnswerOptions values(1,29,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,30,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,30,2,' disagree');
INSERT INTO AnswerOptions values(1,30,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,30,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,30,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,30,6,'agree');
INSERT INTO AnswerOptions values(1,30,7,'strongly agree');
INSERT INTO AnswerOptions values(1,30,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,31,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,31,2,' disagree');
INSERT INTO AnswerOptions values(1,31,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,31,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,31,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,31,6,'agree');
INSERT INTO AnswerOptions values(1,31,7,'strongly agree');
INSERT INTO AnswerOptions values(1,31,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,32,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,32,2,' disagree');
INSERT INTO AnswerOptions values(1,32,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,32,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,32,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,32,6,'agree');
INSERT INTO AnswerOptions values(1,32,7,'strongly agree');
INSERT INTO AnswerOptions values(1,32,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,33,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,33,2,' disagree');
INSERT INTO AnswerOptions values(1,33,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,33,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,33,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,33,6,'agree');
INSERT INTO AnswerOptions values(1,33,7,'strongly agree');
INSERT INTO AnswerOptions values(1,33,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,34,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,34,2,' disagree');
INSERT INTO AnswerOptions values(1,34,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,34,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,34,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,34,6,'agree');
INSERT INTO AnswerOptions values(1,34,7,'strongly agree');
INSERT INTO AnswerOptions values(1,34,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,35,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,35,2,' disagree');
INSERT INTO AnswerOptions values(1,35,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,35,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,35,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,35,6,'agree');
INSERT INTO AnswerOptions values(1,35,7,'strongly agree');
INSERT INTO AnswerOptions values(1,35,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,36,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,36,2,' disagree');
INSERT INTO AnswerOptions values(1,36,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,36,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,36,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,36,6,'agree');
INSERT INTO AnswerOptions values(1,36,7,'strongly agree');
INSERT INTO AnswerOptions values(1,36,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,37,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,37,2,' disagree');
INSERT INTO AnswerOptions values(1,37,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,37,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,37,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,37,6,'agree');
INSERT INTO AnswerOptions values(1,37,7,'strongly agree');
INSERT INTO AnswerOptions values(1,37,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,38,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,38,2,' disagree');
INSERT INTO AnswerOptions values(1,38,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,38,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,38,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,38,6,'agree');
INSERT INTO AnswerOptions values(1,38,7,'strongly agree');
INSERT INTO AnswerOptions values(1,38,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,39,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,39,2,' disagree');
INSERT INTO AnswerOptions values(1,39,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,39,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,39,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,39,6,'agree');
INSERT INTO AnswerOptions values(1,39,7,'strongly agree');
INSERT INTO AnswerOptions values(1,39,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,40,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,40,2,' disagree');
INSERT INTO AnswerOptions values(1,40,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,40,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,40,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,40,6,'agree');
INSERT INTO AnswerOptions values(1,40,7,'strongly agree');
INSERT INTO AnswerOptions values(1,40,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,41,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,41,2,' disagree');
INSERT INTO AnswerOptions values(1,41,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,41,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,41,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,41,6,'agree');
INSERT INTO AnswerOptions values(1,41,7,'strongly agree');
INSERT INTO AnswerOptions values(1,41,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,42,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,42,2,' disagree');
INSERT INTO AnswerOptions values(1,42,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,42,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,42,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,42,6,'agree');
INSERT INTO AnswerOptions values(1,42,7,'strongly agree');
INSERT INTO AnswerOptions values(1,42,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,43,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,43,2,' disagree');
INSERT INTO AnswerOptions values(1,43,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,43,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,43,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,43,6,'agree');
INSERT INTO AnswerOptions values(1,43,7,'strongly agree');
INSERT INTO AnswerOptions values(1,43,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,44,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,44,2,' disagree');
INSERT INTO AnswerOptions values(1,44,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,44,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,44,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,44,6,'agree');
INSERT INTO AnswerOptions values(1,44,7,'strongly agree');
INSERT INTO AnswerOptions values(1,44,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,45,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,45,2,' disagree');
INSERT INTO AnswerOptions values(1,45,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,45,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,45,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,45,6,'agree');
INSERT INTO AnswerOptions values(1,45,7,'strongly agree');
INSERT INTO AnswerOptions values(1,45,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,46,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,46,2,' disagree');
INSERT INTO AnswerOptions values(1,46,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,46,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,46,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,46,6,'agree');
INSERT INTO AnswerOptions values(1,46,7,'strongly agree');
INSERT INTO AnswerOptions values(1,46,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,47,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,47,2,' disagree');
INSERT INTO AnswerOptions values(1,47,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,47,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,47,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,47,6,'agree');
INSERT INTO AnswerOptions values(1,47,7,'strongly agree');
INSERT INTO AnswerOptions values(1,47,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,48,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,48,2,' disagree');
INSERT INTO AnswerOptions values(1,48,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,48,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,48,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,48,6,'agree');
INSERT INTO AnswerOptions values(1,48,7,'strongly agree');
INSERT INTO AnswerOptions values(1,48,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,49,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,49,2,' disagree');
INSERT INTO AnswerOptions values(1,49,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,49,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,49,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,49,6,'agree');
INSERT INTO AnswerOptions values(1,49,7,'strongly agree');
INSERT INTO AnswerOptions values(1,49,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,50,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,50,2,' disagree');
INSERT INTO AnswerOptions values(1,50,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,50,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,50,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,50,6,'agree');
INSERT INTO AnswerOptions values(1,50,7,'strongly agree');
INSERT INTO AnswerOptions values(1,50,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,51,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,51,2,' disagree');
INSERT INTO AnswerOptions values(1,51,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,51,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,51,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,51,6,'agree');
INSERT INTO AnswerOptions values(1,51,7,'strongly agree');
INSERT INTO AnswerOptions values(1,51,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,52,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,52,2,' disagree');
INSERT INTO AnswerOptions values(1,52,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,52,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,52,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,52,6,'agree');
INSERT INTO AnswerOptions values(1,52,7,'strongly agree');
INSERT INTO AnswerOptions values(1,52,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,53,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,53,2,' disagree');
INSERT INTO AnswerOptions values(1,53,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,53,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,53,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,53,6,'agree');
INSERT INTO AnswerOptions values(1,53,7,'strongly agree');
INSERT INTO AnswerOptions values(1,53,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,54,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,54,2,' disagree');
INSERT INTO AnswerOptions values(1,54,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,54,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,54,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,54,6,'agree');
INSERT INTO AnswerOptions values(1,54,7,'strongly agree');
INSERT INTO AnswerOptions values(1,54,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,55,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,55,2,' disagree');
INSERT INTO AnswerOptions values(1,55,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,55,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,55,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,55,6,'agree');
INSERT INTO AnswerOptions values(1,55,7,'strongly agree');
INSERT INTO AnswerOptions values(1,55,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,56,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,56,2,' disagree');
INSERT INTO AnswerOptions values(1,56,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,56,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,56,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,56,6,'agree');
INSERT INTO AnswerOptions values(1,56,7,'strongly agree');
INSERT INTO AnswerOptions values(1,56,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,57,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,57,2,' disagree');
INSERT INTO AnswerOptions values(1,57,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,57,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,57,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,57,6,'agree');
INSERT INTO AnswerOptions values(1,57,7,'strongly agree');
INSERT INTO AnswerOptions values(1,57,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,58,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,58,2,' disagree');
INSERT INTO AnswerOptions values(1,58,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,58,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,58,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,58,6,'agree');
INSERT INTO AnswerOptions values(1,58,7,'strongly agree');
INSERT INTO AnswerOptions values(1,58,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,59,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,59,2,' disagree');
INSERT INTO AnswerOptions values(1,59,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,59,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,59,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,59,6,'agree');
INSERT INTO AnswerOptions values(1,59,7,'strongly agree');
INSERT INTO AnswerOptions values(1,59,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,60,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,60,2,' disagree');
INSERT INTO AnswerOptions values(1,60,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,60,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,60,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,60,6,'agree');
INSERT INTO AnswerOptions values(1,60,7,'strongly agree');
INSERT INTO AnswerOptions values(1,60,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,61,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,61,2,' disagree');
INSERT INTO AnswerOptions values(1,61,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,61,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,61,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,61,6,'agree');
INSERT INTO AnswerOptions values(1,61,7,'strongly agree');
INSERT INTO AnswerOptions values(1,61,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,62,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,62,2,' disagree');
INSERT INTO AnswerOptions values(1,62,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,62,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,62,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,62,6,'agree');
INSERT INTO AnswerOptions values(1,62,7,'strongly agree');
INSERT INTO AnswerOptions values(1,62,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,63,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,63,2,' disagree');
INSERT INTO AnswerOptions values(1,63,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,63,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,63,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,63,6,'agree');
INSERT INTO AnswerOptions values(1,63,7,'strongly agree');
INSERT INTO AnswerOptions values(1,63,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,64,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,64,2,' disagree');
INSERT INTO AnswerOptions values(1,64,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,64,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,64,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,64,6,'agree');
INSERT INTO AnswerOptions values(1,64,7,'strongly agree');
INSERT INTO AnswerOptions values(1,64,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,65,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,65,2,' disagree');
INSERT INTO AnswerOptions values(1,65,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,65,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,65,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,65,6,'agree');
INSERT INTO AnswerOptions values(1,65,7,'strongly agree');
INSERT INTO AnswerOptions values(1,65,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,66,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,66,2,' disagree');
INSERT INTO AnswerOptions values(1,66,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,66,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,66,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,66,6,'agree');
INSERT INTO AnswerOptions values(1,66,7,'strongly agree');
INSERT INTO AnswerOptions values(1,66,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,67,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,67,2,' disagree');
INSERT INTO AnswerOptions values(1,67,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,67,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,67,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,67,6,'agree');
INSERT INTO AnswerOptions values(1,67,7,'strongly agree');
INSERT INTO AnswerOptions values(1,67,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,68,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,68,2,' disagree');
INSERT INTO AnswerOptions values(1,68,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,68,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,68,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,68,6,'agree');
INSERT INTO AnswerOptions values(1,68,7,'strongly agree');
INSERT INTO AnswerOptions values(1,68,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,69,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,69,2,' disagree');
INSERT INTO AnswerOptions values(1,69,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,69,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,69,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,69,6,'agree');
INSERT INTO AnswerOptions values(1,69,7,'strongly agree');
INSERT INTO AnswerOptions values(1,69,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,70,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,70,2,' disagree');
INSERT INTO AnswerOptions values(1,70,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,70,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,70,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,70,6,'agree');
INSERT INTO AnswerOptions values(1,70,7,'strongly agree');
INSERT INTO AnswerOptions values(1,70,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,71,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,71,2,' disagree');
INSERT INTO AnswerOptions values(1,71,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,71,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,71,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,71,6,'agree');
INSERT INTO AnswerOptions values(1,71,7,'strongly agree');
INSERT INTO AnswerOptions values(1,71,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,72,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,72,2,' disagree');
INSERT INTO AnswerOptions values(1,72,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,72,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,72,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,72,6,'agree');
INSERT INTO AnswerOptions values(1,72,7,'strongly agree');
INSERT INTO AnswerOptions values(1,72,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,73,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,73,2,' disagree');
INSERT INTO AnswerOptions values(1,73,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,73,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,73,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,73,6,'agree');
INSERT INTO AnswerOptions values(1,73,7,'strongly agree');
INSERT INTO AnswerOptions values(1,73,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,74,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,74,2,' disagree');
INSERT INTO AnswerOptions values(1,74,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,74,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,74,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,74,6,'agree');
INSERT INTO AnswerOptions values(1,74,7,'strongly agree');
INSERT INTO AnswerOptions values(1,74,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,75,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,75,2,' disagree');
INSERT INTO AnswerOptions values(1,75,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,75,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,75,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,75,6,'agree');
INSERT INTO AnswerOptions values(1,75,7,'strongly agree');
INSERT INTO AnswerOptions values(1,75,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,76,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,76,2,' disagree');
INSERT INTO AnswerOptions values(1,76,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,76,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,76,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,76,6,'agree');
INSERT INTO AnswerOptions values(1,76,7,'strongly agree');
INSERT INTO AnswerOptions values(1,76,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,77,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,77,2,' disagree');
INSERT INTO AnswerOptions values(1,77,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,77,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,77,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,77,6,'agree');
INSERT INTO AnswerOptions values(1,77,7,'strongly agree');
INSERT INTO AnswerOptions values(1,77,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,78,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,78,2,' disagree');
INSERT INTO AnswerOptions values(1,78,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,78,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,78,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,78,6,'agree');
INSERT INTO AnswerOptions values(1,78,7,'strongly agree');
INSERT INTO AnswerOptions values(1,78,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,79,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,79,2,' disagree');
INSERT INTO AnswerOptions values(1,79,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,79,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,79,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,79,6,'agree');
INSERT INTO AnswerOptions values(1,79,7,'strongly agree');
INSERT INTO AnswerOptions values(1,79,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,80,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,80,2,' disagree');
INSERT INTO AnswerOptions values(1,80,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,80,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,80,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,80,6,'agree');
INSERT INTO AnswerOptions values(1,80,7,'strongly agree');
INSERT INTO AnswerOptions values(1,80,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,81,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,81,2,' disagree');
INSERT INTO AnswerOptions values(1,81,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,81,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,81,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,81,6,'agree');
INSERT INTO AnswerOptions values(1,81,7,'strongly agree');
INSERT INTO AnswerOptions values(1,81,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,82,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,82,2,' disagree');
INSERT INTO AnswerOptions values(1,82,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,82,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,82,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,82,6,'agree');
INSERT INTO AnswerOptions values(1,82,7,'strongly agree');
INSERT INTO AnswerOptions values(1,82,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,83,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,83,2,' disagree');
INSERT INTO AnswerOptions values(1,83,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,83,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,83,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,83,6,'agree');
INSERT INTO AnswerOptions values(1,83,7,'strongly agree');
INSERT INTO AnswerOptions values(1,83,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,84,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,84,2,' disagree');
INSERT INTO AnswerOptions values(1,84,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,84,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,84,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,84,6,'agree');
INSERT INTO AnswerOptions values(1,84,7,'strongly agree');
INSERT INTO AnswerOptions values(1,84,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,85,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,85,2,' disagree');
INSERT INTO AnswerOptions values(1,85,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,85,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,85,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,85,6,'agree');
INSERT INTO AnswerOptions values(1,85,7,'strongly agree');
INSERT INTO AnswerOptions values(1,85,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,86,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,86,2,' disagree');
INSERT INTO AnswerOptions values(1,86,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,86,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,86,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,86,6,'agree');
INSERT INTO AnswerOptions values(1,86,7,'strongly agree');
INSERT INTO AnswerOptions values(1,86,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,87,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,87,2,' disagree');
INSERT INTO AnswerOptions values(1,87,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,87,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,87,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,87,6,'agree');
INSERT INTO AnswerOptions values(1,87,7,'strongly agree');
INSERT INTO AnswerOptions values(1,87,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,88,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,88,2,' disagree');
INSERT INTO AnswerOptions values(1,88,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,88,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,88,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,88,6,'agree');
INSERT INTO AnswerOptions values(1,88,7,'strongly agree');
INSERT INTO AnswerOptions values(1,88,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,89,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,89,2,' disagree');
INSERT INTO AnswerOptions values(1,89,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,89,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,89,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,89,6,'agree');
INSERT INTO AnswerOptions values(1,89,7,'strongly agree');
INSERT INTO AnswerOptions values(1,89,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,90,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,90,2,' disagree');
INSERT INTO AnswerOptions values(1,90,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,90,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,90,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,90,6,'agree');
INSERT INTO AnswerOptions values(1,90,7,'strongly agree');
INSERT INTO AnswerOptions values(1,90,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,91,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,91,2,' disagree');
INSERT INTO AnswerOptions values(1,91,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,91,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,91,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,91,6,'agree');
INSERT INTO AnswerOptions values(1,91,7,'strongly agree');
INSERT INTO AnswerOptions values(1,91,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,92,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,92,2,' disagree');
INSERT INTO AnswerOptions values(1,92,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,92,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,92,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,92,6,'agree');
INSERT INTO AnswerOptions values(1,92,7,'strongly agree');
INSERT INTO AnswerOptions values(1,92,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,93,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,93,2,' disagree');
INSERT INTO AnswerOptions values(1,93,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,93,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,93,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,93,6,'agree');
INSERT INTO AnswerOptions values(1,93,7,'strongly agree');
INSERT INTO AnswerOptions values(1,93,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(1,94,1,' strongly disagree ');
INSERT INTO AnswerOptions values(1,94,2,' disagree');
INSERT INTO AnswerOptions values(1,94,3,' somewhat disagree');
INSERT INTO AnswerOptions values(1,94,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(1,94,5,' somewhat agree ');
INSERT INTO AnswerOptions values(1,94,6,'agree');
INSERT INTO AnswerOptions values(1,94,7,'strongly agree');
INSERT INTO AnswerOptions values(1,94,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,7,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,7,2,' disagree');
INSERT INTO AnswerOptions values(2,7,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,7,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,7,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,7,6,'agree');
INSERT INTO AnswerOptions values(2,7,7,'strongly agree');
INSERT INTO AnswerOptions values(2,7,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,8,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,8,2,' disagree');
INSERT INTO AnswerOptions values(2,8,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,8,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,8,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,8,6,'agree');
INSERT INTO AnswerOptions values(2,8,7,'strongly agree');
INSERT INTO AnswerOptions values(2,8,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,9,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,9,2,' disagree');
INSERT INTO AnswerOptions values(2,9,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,9,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,9,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,9,6,'agree');
INSERT INTO AnswerOptions values(2,9,7,'strongly agree');
INSERT INTO AnswerOptions values(2,9,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,10,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,10,2,' disagree');
INSERT INTO AnswerOptions values(2,10,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,10,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,10,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,10,6,'agree');
INSERT INTO AnswerOptions values(2,10,7,'strongly agree');
INSERT INTO AnswerOptions values(2,10,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,11,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,11,2,' disagree');
INSERT INTO AnswerOptions values(2,11,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,11,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,11,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,11,6,'agree');
INSERT INTO AnswerOptions values(2,11,7,'strongly agree');
INSERT INTO AnswerOptions values(2,11,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,12,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,12,2,' disagree');
INSERT INTO AnswerOptions values(2,12,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,12,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,12,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,12,6,'agree');
INSERT INTO AnswerOptions values(2,12,7,'strongly agree');
INSERT INTO AnswerOptions values(2,12,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,13,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,13,2,' disagree');
INSERT INTO AnswerOptions values(2,13,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,13,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,13,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,13,6,'agree');
INSERT INTO AnswerOptions values(2,13,7,'strongly agree');
INSERT INTO AnswerOptions values(2,13,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,14,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,14,2,' disagree');
INSERT INTO AnswerOptions values(2,14,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,14,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,14,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,14,6,'agree');
INSERT INTO AnswerOptions values(2,14,7,'strongly agree');
INSERT INTO AnswerOptions values(2,14,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,15,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,15,2,' disagree');
INSERT INTO AnswerOptions values(2,15,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,15,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,15,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,15,6,'agree');
INSERT INTO AnswerOptions values(2,15,7,'strongly agree');
INSERT INTO AnswerOptions values(2,15,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,16,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,16,2,' disagree');
INSERT INTO AnswerOptions values(2,16,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,16,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,16,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,16,6,'agree');
INSERT INTO AnswerOptions values(2,16,7,'strongly agree');
INSERT INTO AnswerOptions values(2,16,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,17,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,17,2,' disagree');
INSERT INTO AnswerOptions values(2,17,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,17,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,17,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,17,6,'agree');
INSERT INTO AnswerOptions values(2,17,7,'strongly agree');
INSERT INTO AnswerOptions values(2,17,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,18,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,18,2,' disagree');
INSERT INTO AnswerOptions values(2,18,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,18,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,18,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,18,6,'agree');
INSERT INTO AnswerOptions values(2,18,7,'strongly agree');
INSERT INTO AnswerOptions values(2,18,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,19,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,19,2,' disagree');
INSERT INTO AnswerOptions values(2,19,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,19,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,19,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,19,6,'agree');
INSERT INTO AnswerOptions values(2,19,7,'strongly agree');
INSERT INTO AnswerOptions values(2,19,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,20,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,20,2,' disagree');
INSERT INTO AnswerOptions values(2,20,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,20,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,20,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,20,6,'agree');
INSERT INTO AnswerOptions values(2,20,7,'strongly agree');
INSERT INTO AnswerOptions values(2,20,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,21,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,21,2,' disagree');
INSERT INTO AnswerOptions values(2,21,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,21,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,21,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,21,6,'agree');
INSERT INTO AnswerOptions values(2,21,7,'strongly agree');
INSERT INTO AnswerOptions values(2,21,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,22,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,22,2,' disagree');
INSERT INTO AnswerOptions values(2,22,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,22,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,22,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,22,6,'agree');
INSERT INTO AnswerOptions values(2,22,7,'strongly agree');
INSERT INTO AnswerOptions values(2,22,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,23,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,23,2,' disagree');
INSERT INTO AnswerOptions values(2,23,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,23,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,23,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,23,6,'agree');
INSERT INTO AnswerOptions values(2,23,7,'strongly agree');
INSERT INTO AnswerOptions values(2,23,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,24,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,24,2,' disagree');
INSERT INTO AnswerOptions values(2,24,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,24,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,24,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,24,6,'agree');
INSERT INTO AnswerOptions values(2,24,7,'strongly agree');
INSERT INTO AnswerOptions values(2,24,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,25,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,25,2,' disagree');
INSERT INTO AnswerOptions values(2,25,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,25,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,25,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,25,6,'agree');
INSERT INTO AnswerOptions values(2,25,7,'strongly agree');
INSERT INTO AnswerOptions values(2,25,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,26,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,26,2,' disagree');
INSERT INTO AnswerOptions values(2,26,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,26,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,26,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,26,6,'agree');
INSERT INTO AnswerOptions values(2,26,7,'strongly agree');
INSERT INTO AnswerOptions values(2,26,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,27,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,27,2,' disagree');
INSERT INTO AnswerOptions values(2,27,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,27,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,27,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,27,6,'agree');
INSERT INTO AnswerOptions values(2,27,7,'strongly agree');
INSERT INTO AnswerOptions values(2,27,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,28,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,28,2,' disagree');
INSERT INTO AnswerOptions values(2,28,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,28,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,28,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,28,6,'agree');
INSERT INTO AnswerOptions values(2,28,7,'strongly agree');
INSERT INTO AnswerOptions values(2,28,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,29,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,29,2,' disagree');
INSERT INTO AnswerOptions values(2,29,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,29,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,29,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,29,6,'agree');
INSERT INTO AnswerOptions values(2,29,7,'strongly agree');
INSERT INTO AnswerOptions values(2,29,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,30,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,30,2,' disagree');
INSERT INTO AnswerOptions values(2,30,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,30,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,30,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,30,6,'agree');
INSERT INTO AnswerOptions values(2,30,7,'strongly agree');
INSERT INTO AnswerOptions values(2,30,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,31,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,31,2,' disagree');
INSERT INTO AnswerOptions values(2,31,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,31,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,31,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,31,6,'agree');
INSERT INTO AnswerOptions values(2,31,7,'strongly agree');
INSERT INTO AnswerOptions values(2,31,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,32,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,32,2,' disagree');
INSERT INTO AnswerOptions values(2,32,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,32,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,32,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,32,6,'agree');
INSERT INTO AnswerOptions values(2,32,7,'strongly agree');
INSERT INTO AnswerOptions values(2,32,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,33,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,33,2,' disagree');
INSERT INTO AnswerOptions values(2,33,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,33,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,33,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,33,6,'agree');
INSERT INTO AnswerOptions values(2,33,7,'strongly agree');
INSERT INTO AnswerOptions values(2,33,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,34,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,34,2,' disagree');
INSERT INTO AnswerOptions values(2,34,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,34,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,34,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,34,6,'agree');
INSERT INTO AnswerOptions values(2,34,7,'strongly agree');
INSERT INTO AnswerOptions values(2,34,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,35,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,35,2,' disagree');
INSERT INTO AnswerOptions values(2,35,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,35,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,35,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,35,6,'agree');
INSERT INTO AnswerOptions values(2,35,7,'strongly agree');
INSERT INTO AnswerOptions values(2,35,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,36,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,36,2,' disagree');
INSERT INTO AnswerOptions values(2,36,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,36,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,36,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,36,6,'agree');
INSERT INTO AnswerOptions values(2,36,7,'strongly agree');
INSERT INTO AnswerOptions values(2,36,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,37,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,37,2,' disagree');
INSERT INTO AnswerOptions values(2,37,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,37,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,37,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,37,6,'agree');
INSERT INTO AnswerOptions values(2,37,7,'strongly agree');
INSERT INTO AnswerOptions values(2,37,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,38,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,38,2,' disagree');
INSERT INTO AnswerOptions values(2,38,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,38,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,38,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,38,6,'agree');
INSERT INTO AnswerOptions values(2,38,7,'strongly agree');
INSERT INTO AnswerOptions values(2,38,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,39,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,39,2,' disagree');
INSERT INTO AnswerOptions values(2,39,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,39,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,39,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,39,6,'agree');
INSERT INTO AnswerOptions values(2,39,7,'strongly agree');
INSERT INTO AnswerOptions values(2,39,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,40,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,40,2,' disagree');
INSERT INTO AnswerOptions values(2,40,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,40,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,40,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,40,6,'agree');
INSERT INTO AnswerOptions values(2,40,7,'strongly agree');
INSERT INTO AnswerOptions values(2,40,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,41,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,41,2,' disagree');
INSERT INTO AnswerOptions values(2,41,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,41,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,41,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,41,6,'agree');
INSERT INTO AnswerOptions values(2,41,7,'strongly agree');
INSERT INTO AnswerOptions values(2,41,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,42,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,42,2,' disagree');
INSERT INTO AnswerOptions values(2,42,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,42,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,42,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,42,6,'agree');
INSERT INTO AnswerOptions values(2,42,7,'strongly agree');
INSERT INTO AnswerOptions values(2,42,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,43,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,43,2,' disagree');
INSERT INTO AnswerOptions values(2,43,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,43,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,43,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,43,6,'agree');
INSERT INTO AnswerOptions values(2,43,7,'strongly agree');
INSERT INTO AnswerOptions values(2,43,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,44,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,44,2,' disagree');
INSERT INTO AnswerOptions values(2,44,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,44,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,44,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,44,6,'agree');
INSERT INTO AnswerOptions values(2,44,7,'strongly agree');
INSERT INTO AnswerOptions values(2,44,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,45,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,45,2,' disagree');
INSERT INTO AnswerOptions values(2,45,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,45,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,45,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,45,6,'agree');
INSERT INTO AnswerOptions values(2,45,7,'strongly agree');
INSERT INTO AnswerOptions values(2,45,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,46,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,46,2,' disagree');
INSERT INTO AnswerOptions values(2,46,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,46,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,46,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,46,6,'agree');
INSERT INTO AnswerOptions values(2,46,7,'strongly agree');
INSERT INTO AnswerOptions values(2,46,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,47,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,47,2,' disagree');
INSERT INTO AnswerOptions values(2,47,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,47,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,47,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,47,6,'agree');
INSERT INTO AnswerOptions values(2,47,7,'strongly agree');
INSERT INTO AnswerOptions values(2,47,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,48,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,48,2,' disagree');
INSERT INTO AnswerOptions values(2,48,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,48,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,48,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,48,6,'agree');
INSERT INTO AnswerOptions values(2,48,7,'strongly agree');
INSERT INTO AnswerOptions values(2,48,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,49,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,49,2,' disagree');
INSERT INTO AnswerOptions values(2,49,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,49,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,49,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,49,6,'agree');
INSERT INTO AnswerOptions values(2,49,7,'strongly agree');
INSERT INTO AnswerOptions values(2,49,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,50,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,50,2,' disagree');
INSERT INTO AnswerOptions values(2,50,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,50,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,50,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,50,6,'agree');
INSERT INTO AnswerOptions values(2,50,7,'strongly agree');
INSERT INTO AnswerOptions values(2,50,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,51,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,51,2,' disagree');
INSERT INTO AnswerOptions values(2,51,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,51,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,51,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,51,6,'agree');
INSERT INTO AnswerOptions values(2,51,7,'strongly agree');
INSERT INTO AnswerOptions values(2,51,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,52,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,52,2,' disagree');
INSERT INTO AnswerOptions values(2,52,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,52,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,52,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,52,6,'agree');
INSERT INTO AnswerOptions values(2,52,7,'strongly agree');
INSERT INTO AnswerOptions values(2,52,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,53,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,53,2,' disagree');
INSERT INTO AnswerOptions values(2,53,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,53,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,53,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,53,6,'agree');
INSERT INTO AnswerOptions values(2,53,7,'strongly agree');
INSERT INTO AnswerOptions values(2,53,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,54,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,54,2,' disagree');
INSERT INTO AnswerOptions values(2,54,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,54,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,54,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,54,6,'agree');
INSERT INTO AnswerOptions values(2,54,7,'strongly agree');
INSERT INTO AnswerOptions values(2,54,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,55,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,55,2,' disagree');
INSERT INTO AnswerOptions values(2,55,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,55,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,55,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,55,6,'agree');
INSERT INTO AnswerOptions values(2,55,7,'strongly agree');
INSERT INTO AnswerOptions values(2,55,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,56,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,56,2,' disagree');
INSERT INTO AnswerOptions values(2,56,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,56,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,56,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,56,6,'agree');
INSERT INTO AnswerOptions values(2,56,7,'strongly agree');
INSERT INTO AnswerOptions values(2,56,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,57,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,57,2,' disagree');
INSERT INTO AnswerOptions values(2,57,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,57,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,57,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,57,6,'agree');
INSERT INTO AnswerOptions values(2,57,7,'strongly agree');
INSERT INTO AnswerOptions values(2,57,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,58,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,58,2,' disagree');
INSERT INTO AnswerOptions values(2,58,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,58,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,58,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,58,6,'agree');
INSERT INTO AnswerOptions values(2,58,7,'strongly agree');
INSERT INTO AnswerOptions values(2,58,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,59,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,59,2,' disagree');
INSERT INTO AnswerOptions values(2,59,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,59,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,59,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,59,6,'agree');
INSERT INTO AnswerOptions values(2,59,7,'strongly agree');
INSERT INTO AnswerOptions values(2,59,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,60,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,60,2,' disagree');
INSERT INTO AnswerOptions values(2,60,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,60,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,60,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,60,6,'agree');
INSERT INTO AnswerOptions values(2,60,7,'strongly agree');
INSERT INTO AnswerOptions values(2,60,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,61,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,61,2,' disagree');
INSERT INTO AnswerOptions values(2,61,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,61,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,61,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,61,6,'agree');
INSERT INTO AnswerOptions values(2,61,7,'strongly agree');
INSERT INTO AnswerOptions values(2,61,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,62,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,62,2,' disagree');
INSERT INTO AnswerOptions values(2,62,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,62,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,62,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,62,6,'agree');
INSERT INTO AnswerOptions values(2,62,7,'strongly agree');
INSERT INTO AnswerOptions values(2,62,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,63,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,63,2,' disagree');
INSERT INTO AnswerOptions values(2,63,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,63,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,63,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,63,6,'agree');
INSERT INTO AnswerOptions values(2,63,7,'strongly agree');
INSERT INTO AnswerOptions values(2,63,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,64,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,64,2,' disagree');
INSERT INTO AnswerOptions values(2,64,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,64,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,64,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,64,6,'agree');
INSERT INTO AnswerOptions values(2,64,7,'strongly agree');
INSERT INTO AnswerOptions values(2,64,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,65,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,65,2,' disagree');
INSERT INTO AnswerOptions values(2,65,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,65,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,65,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,65,6,'agree');
INSERT INTO AnswerOptions values(2,65,7,'strongly agree');
INSERT INTO AnswerOptions values(2,65,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,66,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,66,2,' disagree');
INSERT INTO AnswerOptions values(2,66,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,66,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,66,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,66,6,'agree');
INSERT INTO AnswerOptions values(2,66,7,'strongly agree');
INSERT INTO AnswerOptions values(2,66,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,67,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,67,2,' disagree');
INSERT INTO AnswerOptions values(2,67,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,67,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,67,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,67,6,'agree');
INSERT INTO AnswerOptions values(2,67,7,'strongly agree');
INSERT INTO AnswerOptions values(2,67,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,68,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,68,2,' disagree');
INSERT INTO AnswerOptions values(2,68,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,68,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,68,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,68,6,'agree');
INSERT INTO AnswerOptions values(2,68,7,'strongly agree');
INSERT INTO AnswerOptions values(2,68,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,69,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,69,2,' disagree');
INSERT INTO AnswerOptions values(2,69,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,69,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,69,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,69,6,'agree');
INSERT INTO AnswerOptions values(2,69,7,'strongly agree');
INSERT INTO AnswerOptions values(2,69,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,70,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,70,2,' disagree');
INSERT INTO AnswerOptions values(2,70,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,70,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,70,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,70,6,'agree');
INSERT INTO AnswerOptions values(2,70,7,'strongly agree');
INSERT INTO AnswerOptions values(2,70,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,71,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,71,2,' disagree');
INSERT INTO AnswerOptions values(2,71,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,71,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,71,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,71,6,'agree');
INSERT INTO AnswerOptions values(2,71,7,'strongly agree');
INSERT INTO AnswerOptions values(2,71,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,72,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,72,2,' disagree');
INSERT INTO AnswerOptions values(2,72,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,72,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,72,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,72,6,'agree');
INSERT INTO AnswerOptions values(2,72,7,'strongly agree');
INSERT INTO AnswerOptions values(2,72,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,73,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,73,2,' disagree');
INSERT INTO AnswerOptions values(2,73,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,73,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,73,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,73,6,'agree');
INSERT INTO AnswerOptions values(2,73,7,'strongly agree');
INSERT INTO AnswerOptions values(2,73,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,74,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,74,2,' disagree');
INSERT INTO AnswerOptions values(2,74,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,74,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,74,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,74,6,'agree');
INSERT INTO AnswerOptions values(2,74,7,'strongly agree');
INSERT INTO AnswerOptions values(2,74,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,75,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,75,2,' disagree');
INSERT INTO AnswerOptions values(2,75,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,75,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,75,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,75,6,'agree');
INSERT INTO AnswerOptions values(2,75,7,'strongly agree');
INSERT INTO AnswerOptions values(2,75,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,76,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,76,2,' disagree');
INSERT INTO AnswerOptions values(2,76,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,76,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,76,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,76,6,'agree');
INSERT INTO AnswerOptions values(2,76,7,'strongly agree');
INSERT INTO AnswerOptions values(2,76,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,77,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,77,2,' disagree');
INSERT INTO AnswerOptions values(2,77,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,77,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,77,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,77,6,'agree');
INSERT INTO AnswerOptions values(2,77,7,'strongly agree');
INSERT INTO AnswerOptions values(2,77,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,78,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,78,2,' disagree');
INSERT INTO AnswerOptions values(2,78,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,78,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,78,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,78,6,'agree');
INSERT INTO AnswerOptions values(2,78,7,'strongly agree');
INSERT INTO AnswerOptions values(2,78,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,79,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,79,2,' disagree');
INSERT INTO AnswerOptions values(2,79,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,79,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,79,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,79,6,'agree');
INSERT INTO AnswerOptions values(2,79,7,'strongly agree');
INSERT INTO AnswerOptions values(2,79,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,80,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,80,2,' disagree');
INSERT INTO AnswerOptions values(2,80,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,80,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,80,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,80,6,'agree');
INSERT INTO AnswerOptions values(2,80,7,'strongly agree');
INSERT INTO AnswerOptions values(2,80,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,81,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,81,2,' disagree');
INSERT INTO AnswerOptions values(2,81,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,81,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,81,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,81,6,'agree');
INSERT INTO AnswerOptions values(2,81,7,'strongly agree');
INSERT INTO AnswerOptions values(2,81,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,82,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,82,2,' disagree');
INSERT INTO AnswerOptions values(2,82,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,82,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,82,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,82,6,'agree');
INSERT INTO AnswerOptions values(2,82,7,'strongly agree');
INSERT INTO AnswerOptions values(2,82,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,83,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,83,2,' disagree');
INSERT INTO AnswerOptions values(2,83,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,83,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,83,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,83,6,'agree');
INSERT INTO AnswerOptions values(2,83,7,'strongly agree');
INSERT INTO AnswerOptions values(2,83,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,84,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,84,2,' disagree');
INSERT INTO AnswerOptions values(2,84,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,84,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,84,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,84,6,'agree');
INSERT INTO AnswerOptions values(2,84,7,'strongly agree');
INSERT INTO AnswerOptions values(2,84,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,85,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,85,2,' disagree');
INSERT INTO AnswerOptions values(2,85,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,85,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,85,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,85,6,'agree');
INSERT INTO AnswerOptions values(2,85,7,'strongly agree');
INSERT INTO AnswerOptions values(2,85,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,86,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,86,2,' disagree');
INSERT INTO AnswerOptions values(2,86,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,86,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,86,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,86,6,'agree');
INSERT INTO AnswerOptions values(2,86,7,'strongly agree');
INSERT INTO AnswerOptions values(2,86,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,87,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,87,2,' disagree');
INSERT INTO AnswerOptions values(2,87,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,87,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,87,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,87,6,'agree');
INSERT INTO AnswerOptions values(2,87,7,'strongly agree');
INSERT INTO AnswerOptions values(2,87,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,88,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,88,2,' disagree');
INSERT INTO AnswerOptions values(2,88,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,88,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,88,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,88,6,'agree');
INSERT INTO AnswerOptions values(2,88,7,'strongly agree');
INSERT INTO AnswerOptions values(2,88,0,'Prefer not to answer');
INSERT INTO AnswerOptions values(2,89,1,' strongly disagree ');
INSERT INTO AnswerOptions values(2,89,2,' disagree');
INSERT INTO AnswerOptions values(2,89,3,' somewhat disagree');
INSERT INTO AnswerOptions values(2,89,4,' neither agree nor disagree ');
INSERT INTO AnswerOptions values(2,89,5,' somewhat agree ');
INSERT INTO AnswerOptions values(2,89,6,'agree');
INSERT INTO AnswerOptions values(2,89,7,'strongly agree');
INSERT INTO AnswerOptions values(2,89,0,'Prefer not to answer');
