INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',1,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Professional Development',1,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',2,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','What I like',2,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',3,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Best Internship',5,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',6,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','My Internship',7,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','High Tech Career',8,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','High Tech Career',9,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Lab Tech Job',9,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',10,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Work-life balance',10,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','My future career',10,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',14,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',15,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Work-life balance',15,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Future Career',17,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',20,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Things I would like to avoid',21,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',21,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',22,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','After graduation',10,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Bad Jobs',23,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',25,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','After graduation',4,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Career',4,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Bad Jobs',5,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Dream Job',7,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Career 1',7,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Career 2',7,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Work-life balance',8,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','I do not want to work',10,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Work-life balance',11,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','I do not want to work',12,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','If i did want to work',12,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Job in sunny California',13,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','My Career plan ',16,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','In search of a good job',17,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Active job',18,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Job #4',19,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Profile #5',20,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Yawn',24,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','CEO track',24,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','I do not want to work',25,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Job #2',12,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','My last profile',12,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Huh',22,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Huh 2',22,'Desired');
INSERT INTO Profile (dateCreated, name, accountID, profileType) values('2022-05-19','Work-life balance',23,'Desired');
